# Generated by Django 5.1.4 on 2025-01-08 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('width', models.FloatField(help_text='Width of the site in mm')),
                ('length', models.FloatField(help_text='Length of the site in mm')),
                ('height', models.FloatField(help_text='Height of the site in mm')),
                ('wall_thickness', models.FloatField(default=200.0, help_text='Default wall thickness in mm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_x', models.FloatField(help_text="X-coordinate of the wall's start point")),
                ('start_y', models.FloatField(help_text="Y-coordinate of the wall's start point")),
                ('end_x', models.FloatField(help_text="X-coordinate of the wall's end point")),
                ('end_y', models.FloatField(help_text="Y-coordinate of the wall's end point")),
                ('thickness', models.FloatField(default=200.0, help_text='Wall thickness in mm')),
                ('is_default', models.BooleanField(default=True, help_text='True if the wall is a default boundary wall')),
                ('has_concrete_base', models.BooleanField(default=False, help_text='Whether the wall has a concrete base')),
                ('concrete_base_height', models.FloatField(blank=True, help_text='Height of the concrete base in mm', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walls', to='core.project')),
            ],
        ),
    ]
