# Generated by Django 5.1.4 on 2025-01-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall',
            name='height',
            field=models.FloatField(default=1000.0),
        ),
    ]
