# Generated by Django 5.1.4 on 2025-01-15 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_wall_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('floor_type', models.CharField(default='default', help_text='Type of the floor', max_length=100)),
                ('floor_thickness', models.FloatField(default=0.1, help_text='Thickness of the floor in mm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.project')),
                ('walls', models.ManyToManyField(related_name='rooms', to='core.wall')),
            ],
        ),
    ]
