# Generated by Django 5.1.4 on 2025-01-15 07:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='height',
            field=models.DecimalField(decimal_places=2, help_text='Height of the site in mm', max_digits=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='length',
            field=models.DecimalField(decimal_places=2, help_text='Length of the site in mm', max_digits=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='wall_thickness',
            field=models.DecimalField(decimal_places=2, default=Decimal('200.00'), help_text='Default wall thickness in mm', max_digits=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='width',
            field=models.DecimalField(decimal_places=2, help_text='Width of the site in mm', max_digits=10),
        ),
        migrations.AlterField(
            model_name='wall',
            name='concrete_base_height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height of the concrete base in mm', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='wall',
            name='end_x',
            field=models.DecimalField(decimal_places=3, help_text="X-coordinate of the wall's end point", max_digits=12),
        ),
        migrations.AlterField(
            model_name='wall',
            name='end_y',
            field=models.DecimalField(decimal_places=3, help_text="Y-coordinate of the wall's end point", max_digits=12),
        ),
        migrations.AlterField(
            model_name='wall',
            name='height',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Wall height in mm', max_digits=10),
        ),
        migrations.AlterField(
            model_name='wall',
            name='start_x',
            field=models.DecimalField(decimal_places=3, help_text="X-coordinate of the wall's start point", max_digits=12),
        ),
        migrations.AlterField(
            model_name='wall',
            name='start_y',
            field=models.DecimalField(decimal_places=3, help_text="Y-coordinate of the wall's start point", max_digits=12),
        ),
        migrations.AlterField(
            model_name='wall',
            name='thickness',
            field=models.DecimalField(decimal_places=2, default=Decimal('200.00'), help_text='Wall thickness in mm', max_digits=10),
        ),
    ]
