# Generated by Django 5.1.4 on 2025-01-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_project_height_alter_project_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='height',
            field=models.FloatField(help_text='Height of the site in mm'),
        ),
        migrations.AlterField(
            model_name='project',
            name='length',
            field=models.FloatField(help_text='Length of the site in mm'),
        ),
        migrations.AlterField(
            model_name='project',
            name='wall_thickness',
            field=models.FloatField(default=200.0, help_text='Default wall thickness in mm'),
        ),
        migrations.AlterField(
            model_name='project',
            name='width',
            field=models.FloatField(help_text='Width of the site in mm'),
        ),
        migrations.AlterField(
            model_name='wall',
            name='concrete_base_height',
            field=models.FloatField(blank=True, help_text='Height of the concrete base in mm', null=True),
        ),
        migrations.AlterField(
            model_name='wall',
            name='end_x',
            field=models.FloatField(help_text="X-coordinate of the wall's end point"),
        ),
        migrations.AlterField(
            model_name='wall',
            name='end_y',
            field=models.FloatField(help_text="Y-coordinate of the wall's end point"),
        ),
        migrations.AlterField(
            model_name='wall',
            name='height',
            field=models.FloatField(default=1000.0),
        ),
        migrations.AlterField(
            model_name='wall',
            name='start_x',
            field=models.FloatField(help_text="X-coordinate of the wall's start point"),
        ),
        migrations.AlterField(
            model_name='wall',
            name='start_y',
            field=models.FloatField(help_text="Y-coordinate of the wall's start point"),
        ),
        migrations.AlterField(
            model_name='wall',
            name='thickness',
            field=models.FloatField(default=200.0, help_text='Wall thickness in mm'),
        ),
    ]
