# Generated by Django 5.1.4 on 2025-01-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_project_height_alter_project_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
