# Generated by Django 5.1.4 on 2025-02-05 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_name_room_room_name_remove_room_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall',
            name='application_type',
            field=models.CharField(choices=[('wall', 'Wall'), ('partition', 'Partition')], default='wall', help_text='Specify whether this is a wall or a partition.', max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor_thickness',
            field=models.DecimalField(decimal_places=2, help_text='Floor thickness in mm', max_digits=5),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor_type',
            field=models.CharField(choices=[('slab', 'Slab'), ('panel', 'Panel'), ('none', 'None')], default='none', help_text='Specify the type of floor for the room.', max_length=50),
        ),
        migrations.AlterField(
            model_name='wall',
            name='height',
            field=models.FloatField(default=1000.0, help_text='Height of the wall in mm'),
        ),
        migrations.CreateModel(
            name='Ceiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness', models.FloatField(help_text='Thickness of the ceiling in mm')),
                ('length', models.FloatField(help_text='Length of the ceiling in mm')),
                ('width', models.FloatField(help_text='Width of the ceiling in mm')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ceilings', to='core.room')),
            ],
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_type', models.CharField(choices=[('sweep', 'Sweep Door'), ('slide', 'Slide Door')], default='sweep', help_text='Specify the type of door.', max_length=50)),
                ('configuration', models.CharField(choices=[('single_sided', 'Single-Sided'), ('double_sided', 'Double-Sided')], default='single_sided', help_text='Specify the configuration of the door.', max_length=50)),
                ('width', models.FloatField(help_text='Width of the door in mm')),
                ('height', models.FloatField(help_text='Height of the door in mm')),
                ('position_x', models.FloatField(help_text="X-coordinate of the door's position")),
                ('position_y', models.FloatField(help_text="Y-coordinate of the door's position")),
                ('orientation', models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical')], default='horizontal', help_text='Orientation of the door in the plan.', max_length=50)),
                ('linked_wall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doors', to='core.wall')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doors', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='Intersection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_method', models.CharField(choices=[('45_cut', '45° Cut'), ('bulk_in', 'Bulk In')], default='bulk_in', help_text='Specify the joining method at this intersection.', max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intersections', to='core.project')),
                ('wall_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intersection_wall_1', to='core.wall')),
                ('wall_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intersection_wall_2', to='core.wall')),
            ],
        ),
    ]
