# Generated by Django 5.1.4 on 2025-02-07 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_room_floor_thickness_alter_room_floor_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Room temperature in °C (Optional).', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor_type',
            field=models.CharField(choices=[('Slab', 'Slab'), ('Panel', 'Panel'), ('None', 'None')], default='None', help_text='Specify the type of floor for the room.', max_length=50),
        ),
    ]
