# Generated by Django 5.1.4 on 2025-03-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_room_temperature_alter_room_floor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intersection',
            name='joining_method',
            field=models.CharField(choices=[('45_cut', '45° Cut'), ('butt_in', 'Butt In')], default='bulk_in', help_text='Specify the joining method at this intersection.', max_length=50),
        ),
    ]
