# Generated by Django 5.1.4 on 2025-03-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_intersection_joining_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intersection',
            options={'ordering': ['wall_1_id', 'wall_2_id']},
        ),
        migrations.AlterField(
            model_name='intersection',
            name='joining_method',
            field=models.CharField(choices=[('45_cut', '45° Cut'), ('butt_in', 'Butt In')], default='butt_in', help_text='Specify the joining method at this intersection.', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='intersection',
            unique_together={('wall_1', 'wall_2')},
        ),
    ]
