# Generated by Django 5.1.4 on 2025-03-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_intersection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='opening_direction',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('double', 'Double')], default='left', help_text='Door opening direction', max_length=20),
        ),
        migrations.AddField(
            model_name='door',
            name='position_along_wall',
            field=models.FloatField(default=0.5, help_text='Position along wall (0-1 ratio)'),
        ),
    ]
