# Generated by Django 5.1.4 on 2025-03-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_door_opening_direction_door_position_along_wall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='door',
            name='opening_direction',
        ),
        migrations.RemoveField(
            model_name='door',
            name='position_along_wall',
        ),
        migrations.AddField(
            model_name='door',
            name='side',
            field=models.CharField(choices=[('interior', 'Interior'), ('exterior', 'Exterior')], default='interior', help_text='Specify if the door opens to the interior or exterior side.', max_length=20),
        ),
        migrations.AddField(
            model_name='door',
            name='slide_direction',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='right', help_text='Sliding direction for slide doors.', max_length=20),
        ),
        migrations.AddField(
            model_name='door',
            name='swing_direction',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='right', help_text='Swing direction for sweep doors.', max_length=20),
        ),
    ]
