# Generated by Django 5.1.4 on 2025-03-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_door_opening_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='door_type',
            field=models.CharField(choices=[('swing', 'Swing Door'), ('slide', 'Slide Door')], default='sweep', help_text='Specify the type of door.', max_length=50),
        ),
    ]
