# Generated by Django 5.1.4 on 2025-04-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_door_door_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='thickness',
            field=models.FloatField(default=100, help_text='thickness of the Door Panel in mm'),
            preserve_default=False,
        ),
    ]
