# Generated by Django 5.1.4 on 2025-04-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_door_thickness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='slide_direction',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], default='right', help_text='Sliding direction for slide doors.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='door',
            name='swing_direction',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], default='right', help_text='Swing direction for sweep doors.', max_length=20, null=True),
        ),
    ]
