# Generated by Django 5.1.4 on 2025-04-08 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_intersection_options_intersection_point_x_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intersection',
            name='point_x',
        ),
        migrations.RemoveField(
            model_name='intersection',
            name='point_y',
        ),
    ]
