# Generated by Django 5.1.4 on 2025-04-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_intersection_point_x_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='intersection',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='intersection',
            name='x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='intersection',
            name='y',
            field=models.FloatField(null=True),
        ),
        migrations.AddConstraint(
            model_name='intersection',
            constraint=models.UniqueConstraint(fields=('wall_1', 'wall_2', 'x', 'y'), name='unique_wall_pair_at_point'),
        ),
    ]
