# Generated by Django 5.1.4 on 2025-04-09 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_intersection_unique_together_intersection_x_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='intersection',
            name='unique_wall_pair_at_point',
        ),
        migrations.AlterUniqueTogether(
            name='intersection',
            unique_together={('wall_1', 'wall_2')},
        ),
        migrations.RemoveField(
            model_name='intersection',
            name='x',
        ),
        migrations.RemoveField(
            model_name='intersection',
            name='y',
        ),
    ]
