# Generated by Django 5.1.4 on 2025-05-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_intersection_unique_wall_pair_at_point_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='walls',
        ),
        migrations.AddField(
            model_name='room',
            name='outline_points',
            field=models.JSONField(blank=True, help_text='Ordered list of room boundary points as [{x, y}, ...]', null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor_thickness',
            field=models.IntegerField(choices=[(50, '50 mm'), (75, '75 mm'), (100, '100 mm'), (125, '125 mm'), (150, '150 mm'), (175, '175 mm'), (200, '200 mm')]),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor_type',
            field=models.CharField(choices=[('Slab', 'Slab'), ('Panel', 'Panel'), ('None', 'None')], default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
