# Generated by Django 5.1.4 on 2025-05-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_room_walls_room_outline_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor_thickness',
            field=models.IntegerField(choices=[(0, 'None'), (50, '50 mm'), (75, '75 mm'), (100, '100 mm'), (125, '125 mm'), (150, '150 mm'), (175, '175 mm'), (200, '200 mm')]),
        ),
    ]
