# Generated by Django 5.1.4 on 2025-05-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_room_floor_thickness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='outline_points',
        ),
        migrations.AddField(
            model_name='room',
            name='walls',
            field=models.ManyToManyField(related_name='rooms', to='core.wall'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor_thickness',
            field=models.IntegerField(choices=[(50, '50 mm'), (75, '75 mm'), (100, '100 mm'), (125, '125 mm'), (150, '150 mm'), (175, '175 mm'), (200, '200 mm')], help_text='Floor thickness in mm (select from predefined values).'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor_type',
            field=models.CharField(choices=[('Slab', 'Slab'), ('Panel', 'Panel'), ('None', 'None')], default='None', help_text='Specify the type of floor for the room.', max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Room temperature in °C (Optional).', max_digits=5, null=True),
        ),
    ]
