# Generated by Django 5.1.4 on 2025-05-08 13:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_room_outline_points_room_walls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_points',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, help_text='List of points {x, y} defining the room boundary', size=None),
        ),
    ]
