# Generated by Django 5.1.4 on 2025-08-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='height',
            field=models.FloatField(blank=True, help_text='Height of the room in mm (will be set to minimum wall height if not specified)', null=True),
        ),
    ]
