# Generated by Django 5.1.4 on 2025-08-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_add_room_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='label_position',
            field=models.JSONField(blank=True, help_text='Position {x, y} of the room label on the canvas', null=True),
        ),
    ]
