# Generated by Django 5.1.4 on 2025-08-14 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_add_room_label_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor_thickness',
            field=models.IntegerField(choices=[(0, 'None'), (50, '50 mm'), (75, '75 mm'), (100, '100 mm'), (125, '125 mm'), (150, '150 mm'), (175, '175 mm'), (200, '200 mm')], help_text='Floor thickness in mm (select from predefined values).'),
        ),
    ]
