# Generated by Django 5.1.4 on 2025-08-16 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_add_none_floor_thickness'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeilingPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_id', models.CharField(help_text='Unique identifier for the panel', max_length=50)),
                ('start_x', models.FloatField(help_text="X-coordinate of the panel's start point")),
                ('start_y', models.FloatField(help_text="Y-coordinate of the panel's start point")),
                ('end_x', models.FloatField(help_text="X-coordinate of the panel's end point")),
                ('end_y', models.FloatField(help_text="Y-coordinate of the panel's end point")),
                ('width', models.FloatField(help_text='Width of the panel in mm (max 1150mm)')),
                ('length', models.FloatField(help_text='Length of the panel in mm')),
                ('thickness', models.FloatField(default=20.0, help_text='Thickness of the ceiling panel in mm')),
                ('material_type', models.CharField(choices=[('standard', 'Standard Panel'), ('acoustic', 'Acoustic Panel'), ('fire_rated', 'Fire Rated Panel'), ('moisture_resistant', 'Moisture Resistant Panel')], default='standard', max_length=50)),
                ('is_cut_panel', models.BooleanField(default=False, help_text='Whether this panel was cut to fit')),
                ('cut_notes', models.TextField(blank=True, help_text='Notes about any cuts made to the panel', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ceiling_panels', to='core.room')),
            ],
            options={
                'unique_together': {('room', 'panel_id')},
            },
        ),
        migrations.CreateModel(
            name='CeilingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_area', models.FloatField(help_text='Total ceiling area in square mm')),
                ('total_panels', models.IntegerField(default=0, help_text='Total number of panels used')),
                ('full_panels', models.IntegerField(default=0, help_text='Number of full panels used')),
                ('cut_panels', models.IntegerField(default=0, help_text='Number of cut panels used')),
                ('waste_percentage', models.FloatField(default=0.0, help_text='Percentage of material wasted')),
                ('generation_method', models.CharField(choices=[('automatic', 'Automatic Generation'), ('manual', 'Manual Placement'), ('hybrid', 'Hybrid (Auto + Manual)')], default='automatic', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the ceiling plan', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ceiling_plan', to='core.room')),
            ],
        ),
        migrations.DeleteModel(
            name='Ceiling',
        ),
    ]
