# Generated by Django 5.1.4 on 2025-08-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_add_new_ceiling_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceilingplan',
            name='ceiling_thickness',
            field=models.FloatField(default=150, help_text='Ceiling thickness used for this plan (critical for 3D generation)'),
        ),
        migrations.AddField(
            model_name='ceilingplan',
            name='custom_panel_length',
            field=models.FloatField(blank=True, help_text='Custom panel length if not auto', null=True),
        ),
        migrations.AddField(
            model_name='ceilingplan',
            name='orientation_strategy',
            field=models.CharField(default='auto', help_text='Orientation strategy used for panel layout', max_length=50),
        ),
        migrations.AddField(
            model_name='ceilingplan',
            name='panel_length',
            field=models.CharField(default='auto', help_text='Panel length setting used for this plan', max_length=20),
        ),
        migrations.AddField(
            model_name='ceilingplan',
            name='panel_width',
            field=models.FloatField(default=1150, help_text='Panel width used for this plan'),
        ),
        migrations.AddField(
            model_name='ceilingplan',
            name='support_config',
            field=models.JSONField(default=dict, help_text='Support configuration options used'),
        ),
        migrations.AddField(
            model_name='ceilingplan',
            name='support_type',
            field=models.CharField(default='nylon', help_text='Support system type used', max_length=20),
        ),
    ]
