# Generated by Django 5.1.4 on 2025-08-29 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_add_ceiling_plan_generation_parameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_area', models.FloatField(help_text='Total floor area in square mm (excluding walls)')),
                ('total_panels', models.IntegerField(default=0, help_text='Total number of floor panels used')),
                ('full_panels', models.IntegerField(default=0, help_text='Number of full floor panels used')),
                ('cut_panels', models.IntegerField(default=0, help_text='Number of cut floor panels used')),
                ('waste_percentage', models.FloatField(default=0.0, help_text='Percentage of material wasted')),
                ('generation_method', models.CharField(choices=[('automatic', 'Automatic Generation'), ('manual', 'Manual Placement'), ('hybrid', 'Hybrid (Auto + Manual)')], default='automatic', max_length=50)),
                ('floor_thickness', models.FloatField(default=150, help_text='Floor thickness used for this plan (critical for 3D generation)')),
                ('orientation_strategy', models.CharField(default='auto', help_text='Orientation strategy used for floor panel layout', max_length=50)),
                ('panel_width', models.FloatField(default=1150, help_text='Floor panel width used for this plan')),
                ('panel_length', models.CharField(default='auto', help_text='Floor panel length setting used for this plan', max_length=20)),
                ('custom_panel_length', models.FloatField(blank=True, help_text='Custom floor panel length if not auto', null=True)),
                ('floor_type', models.CharField(choices=[('standard', 'Standard Floor'), ('waterproof', 'Waterproof Floor'), ('acoustic', 'Acoustic Floor'), ('heated', 'Heated Floor'), ('insulated', 'Insulated Floor')], default='standard', help_text='Type of floor system used', max_length=50)),
                ('underlayment', models.CharField(choices=[('none', 'No Underlayment'), ('foam', 'Foam Underlayment'), ('cork', 'Cork Underlayment'), ('rubber', 'Rubber Underlayment'), ('acoustic', 'Acoustic Underlayment')], default='none', help_text='Type of underlayment used', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the floor plan', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plan', to='core.room')),
            ],
        ),
        migrations.CreateModel(
            name='FloorPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_id', models.CharField(help_text='Unique identifier for the floor panel', max_length=50)),
                ('start_x', models.FloatField(help_text="X-coordinate of the panel's start point")),
                ('start_y', models.FloatField(help_text="Y-coordinate of the panel's start point")),
                ('end_x', models.FloatField(help_text="X-coordinate of the panel's end point")),
                ('end_y', models.FloatField(help_text="Y-coordinate of the panel's end point")),
                ('width', models.FloatField(help_text='Width of the floor panel in mm')),
                ('length', models.FloatField(help_text='Length of the floor panel in mm')),
                ('thickness', models.FloatField(default=20.0, help_text='Thickness of the floor panel in mm')),
                ('material_type', models.CharField(choices=[('standard', 'Standard Floor Panel'), ('waterproof', 'Waterproof Panel'), ('acoustic', 'Acoustic Panel'), ('heated', 'Heated Floor Panel'), ('insulated', 'Insulated Panel')], default='standard', max_length=50)),
                ('is_cut_panel', models.BooleanField(default=False, help_text='Whether this panel was cut to fit')),
                ('cut_notes', models.TextField(blank=True, help_text='Notes about any cuts made to the panel', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_panels', to='core.room')),
            ],
            options={
                'unique_together': {('room', 'panel_id')},
            },
        ),
    ]
