# Generated by Django 5.1.4 on 2025-08-29 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_add_floor_plan_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floorplan',
            name='floor_thickness',
        ),
        migrations.RemoveField(
            model_name='floorplan',
            name='floor_type',
        ),
        migrations.RemoveField(
            model_name='floorplan',
            name='underlayment',
        ),
    ]
