# Generated by Django 5.1.4 on 2025-08-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_floor_settings_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorplan',
            name='total_area',
            field=models.FloatField(default=0.0, help_text='Total floor area in square mm (excluding walls)'),
        ),
    ]
