# Generated by Django 5.1.4 on 2025-10-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_add_total_area_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceilingpanel',
            name='full_panel_length',
            field=models.FloatField(blank=True, help_text='Full panel length purchased (for waste calculation)', null=True),
        ),
        migrations.AddField(
            model_name='ceilingpanel',
            name='full_panel_width',
            field=models.FloatField(blank=True, help_text='Full panel width purchased (for waste calculation)', null=True),
        ),
    ]
