# Generated by Django 5.1.4 on 2025-10-13 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_ceilingpanel_full_panel_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ceilingpanel',
            name='full_panel_length',
        ),
        migrations.RemoveField(
            model_name='ceilingpanel',
            name='full_panel_width',
        ),
    ]
