# Generated by Django 5.1.4 on 2025-10-27 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_ceilingpanel_full_panel_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall',
            name='fill_gap_mode',
            field=models.BooleanField(default=False, help_text='Fill only the gap between rooms with different heights'),
        ),
        migrations.AddField(
            model_name='wall',
            name='gap_base_position',
            field=models.FloatField(blank=True, help_text='Y position (height) where the gap-fill wall starts in mm', null=True),
        ),
        migrations.AddField(
            model_name='wall',
            name='gap_fill_height',
            field=models.FloatField(blank=True, help_text='Height of the wall when filling gap between rooms in mm', null=True),
        ),
    ]
