# Generated by Django 5.1.4 on 2025-11-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_add_gap_fill_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall',
            name='inner_face_material',
            field=models.CharField(choices=[('PPGI', 'PPGI'), ('S/Steel', 'S/Steel'), ('PVC', 'PVC')], default='PPGI', help_text='Inner face material', max_length=20),
        ),
        migrations.AddField(
            model_name='wall',
            name='inner_face_thickness',
            field=models.FloatField(default=0.5, help_text='Inner face sheet thickness in mm'),
        ),
        migrations.AddField(
            model_name='wall',
            name='outer_face_material',
            field=models.CharField(choices=[('PPGI', 'PPGI'), ('S/Steel', 'S/Steel'), ('PVC', 'PVC')], default='PPGI', help_text='Outer face material', max_length=20),
        ),
        migrations.AddField(
            model_name='wall',
            name='outer_face_thickness',
            field=models.FloatField(default=0.5, help_text='Outer face sheet thickness in mm'),
        ),
    ]
