# Generated by Django 5.1.4 on 2025-11-05 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_wall_inner_face_material_wall_inner_face_thickness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='base_elevation_mm',
            field=models.FloatField(default=0.0, help_text='Base elevation of the room relative to ground level in mm. Positive = raised, Negative = sunken. Default is 0 (ground level).'),
        ),
    ]
