# Generated by Django 5.1.4 on 2025-11-07 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_add_room_base_elevation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceilingpanel',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ceiling_panels', to='core.room'),
        ),
        migrations.AlterField(
            model_name='ceilingplan',
            name='room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ceiling_plan', to='core.room'),
        ),
        migrations.CreateModel(
            name='CeilingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceiling_thickness', models.FloatField(default=150, help_text='Ceiling thickness used for this zone in mm')),
                ('orientation_strategy', models.CharField(default='auto', help_text='Orientation strategy applied to the merged zone', max_length=50)),
                ('panel_width', models.FloatField(default=1150, help_text='Panel width used for this zone')),
                ('panel_length', models.CharField(default='auto', help_text='Panel length setting for this zone', max_length=20)),
                ('custom_panel_length', models.FloatField(blank=True, help_text='Custom panel length if not auto', null=True)),
                ('support_type', models.CharField(default='nylon', help_text='Support system type used', max_length=20)),
                ('support_config', models.JSONField(default=dict, help_text='Support configuration options used')),
                ('outline_points', models.JSONField(default=list, help_text='Ordered list of points defining the merged zone boundary')),
                ('total_area', models.FloatField(default=0.0, help_text='Total ceiling area covered by this zone')),
                ('total_panels', models.IntegerField(default=0, help_text='Total panels used across the zone')),
                ('full_panels', models.IntegerField(default=0, help_text='Number of full panels')),
                ('cut_panels', models.IntegerField(default=0, help_text='Number of cut panels')),
                ('waste_percentage', models.FloatField(default=0.0, help_text='Waste percentage for the zone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ceiling_zones', to='core.project')),
                ('rooms', models.ManyToManyField(related_name='ceiling_zones', to='core.room')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ceilingpanel',
            unique_together={('room', 'panel_id')},
        ),
        migrations.AddField(
            model_name='ceilingpanel',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ceiling_panels', to='core.ceilingzone'),
        ),
        migrations.AddField(
            model_name='ceilingplan',
            name='zone',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ceiling_plan', to='core.ceilingzone'),
        ),
        migrations.AlterUniqueTogether(
            name='ceilingpanel',
            unique_together={('room', 'panel_id'), ('zone', 'panel_id')},
        ),
    ]
