# Generated by Django 5.1.4 on 2025-11-14 01:32

import django.db.models.deletion
from django.db import migrations, models


def bootstrap_storeys(apps, schema_editor):
    Project = apps.get_model('core', 'Project')
    Storey = apps.get_model('core', 'Storey')
    Wall = apps.get_model('core', 'Wall')
    Room = apps.get_model('core', 'Room')
    Door = apps.get_model('core', 'Door')
    CeilingZone = apps.get_model('core', 'CeilingZone')

    for project in Project.objects.all():
        default_height = project.height if project.height else 3000.0
        storey, _ = Storey.objects.get_or_create(
            project=project,
            order=0,
            defaults={
                'name': 'Ground Floor',
                'elevation_mm': 0.0,
                'default_room_height_mm': default_height,
                'slab_thickness_mm': 0.0,
            },
        )

        Wall.objects.filter(project=project, storey__isnull=True).update(storey=storey)
        Room.objects.filter(project=project, storey__isnull=True).update(storey=storey)
        Door.objects.filter(project=project, storey__isnull=True).update(storey=storey)
        CeilingZone.objects.filter(project=project, storey__isnull=True).update(storey=storey)

    # Ensure rooms with null base elevation default to 0.0 for consistent stacking
    Room.objects.filter(base_elevation_mm__isnull=True).update(base_elevation_mm=0.0)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_ceilingpanel_room_alter_ceilingplan_room_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable storey label.', max_length=100)),
                ('elevation_mm', models.FloatField(help_text='Base elevation of the storey relative to project ground level in mm.')),
                ('default_room_height_mm', models.FloatField(default=3000.0, help_text='Default room height for rooms created on this storey in mm.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering index for storeys from lowest to highest.')),
                ('slab_thickness_mm', models.FloatField(default=0.0, help_text='Optional structural thickness between this storey and the one above.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(help_text='Project this storey belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='storeys', to='core.project')),
            ],
            options={
                'ordering': ['order', 'elevation_mm', 'id'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.AddField(
            model_name='ceilingzone',
            name='storey',
            field=models.ForeignKey(blank=True, help_text='Storey this ceiling zone belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ceiling_zones', to='core.storey'),
        ),
        migrations.AddField(
            model_name='door',
            name='storey',
            field=models.ForeignKey(blank=True, help_text='Storey this door resides in.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doors', to='core.storey'),
        ),
        migrations.AddField(
            model_name='room',
            name='storey',
            field=models.ForeignKey(blank=True, help_text='Storey this room resides in.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.storey'),
        ),
        migrations.AddField(
            model_name='wall',
            name='storey',
            field=models.ForeignKey(blank=True, help_text='Storey this wall belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='walls', to='core.storey'),
        ),
        migrations.RunPython(bootstrap_storeys, migrations.RunPython.noop),
    ]
