# Generated by Django 5.1.4 on 2025-11-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_storey_ceilingzone_storey_door_storey_room_storey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='floor_layers',
            field=models.IntegerField(default=1, help_text='Number of layers of floor slabs. Total thickness = floor_thickness × floor_layers'),
        ),
    ]
