# Generated by Django 5.1.4 on 2025-12-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_wall_base_elevation_if_exists'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall',
            name='ceiling_cut_l_horizontal_extension',
            field=models.FloatField(blank=True, help_text='Horizontal extension for Cut L joint type in mm (defaults based on wall thickness if not specified)', null=True),
        ),
        migrations.AddField(
            model_name='wall',
            name='ceiling_joint_type',
            field=models.CharField(blank=True, choices=[('AA11', 'AA11 - No cutting, directly on top'), ('cut_l', 'Cut L - L-shaped cut in wall'), ('cut_45', 'Cut 45 - 45-degree cut')], help_text='How the ceiling joins with this wall: AA11 (no cutting), Cut L (L-shaped cut), or Cut 45 (45-degree cut)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='intersection',
            name='joining_method',
            field=models.CharField(choices=[('none', 'None'), ('butt_in', 'Butt-in'), ('45_cut', '45° Cut')], max_length=20),
        ),
    ]
