# Generated by Django 5.1.4 on 2026-01-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_add_ceiling_joint_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceilingpanel',
            name='shape_data',
            field=models.JSONField(blank=True, help_text='List of {x,y} points defining the exact polygon shape for non-rectangular panels', null=True),
        ),
        migrations.AlterField(
            model_name='door',
            name='door_type',
            field=models.CharField(choices=[('swing', 'Swing Door'), ('slide', 'Slide Door'), ('dock', 'Dock Door')], default='swing', help_text='Specify the type of door.', max_length=50),
        ),
    ]
