# Generated by Django 5.1.4 on 2026-01-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_ceilingpanel_shape_data_alter_door_door_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorpanel',
            name='shape_points',
            field=models.JSONField(blank=True, help_text="List of vertices [{'x': x, 'y': y}, ...] defining the actual cut shape.", null=True),
        ),
    ]
