# Generated by Django 5.1.4 on 2026-01-01 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_floorpanel_shape_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floorpanel',
            name='shape_points',
        ),
    ]
