# Generated by Django 5.1.4 on 2026-01-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_remove_floorpanel_shape_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='allow_variable_wall_heights',
            field=models.BooleanField(default=False, help_text='If True, allows walls in this room to have different heights (for sloped roofs). When enabled, room height updates will not automatically modify wall heights.'),
        ),
    ]
