# Generated by Django 5.1.4 on 2026-01-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_add_allow_variable_wall_heights_to_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall',
            name='base_elevation_mm',
            field=models.FloatField(default=0.0, help_text='Base elevation of the wall relative to ground level in mm. Set automatically based on room base elevations, or 0 if not related to any room.'),
        ),
        migrations.RunPython(
            # Update existing walls' base_elevation_mm based on room relationships
            code=lambda apps, schema_editor: update_wall_base_elevations_migration(apps, schema_editor),
            reverse_code=migrations.RunPython.noop,
        ),
    ]


def update_wall_base_elevations_migration(apps, schema_editor):
    """Update base_elevation_mm for all existing walls based on room relationships."""
    Wall = apps.get_model('core', 'Wall')
    Room = apps.get_model('core', 'Room')
    
    walls = Wall.objects.all().prefetch_related('rooms')
    updated_count = 0
    
    for wall in walls:
        # Get all rooms that contain this wall
        rooms_containing_wall = wall.rooms.all()
        
        if rooms_containing_wall.exists():
            # Use the minimum base elevation of all rooms containing this wall
            base_elevations = [
                room.base_elevation_mm for room in rooms_containing_wall 
                if room.base_elevation_mm is not None
            ]
            
            if base_elevations:
                wall.base_elevation_mm = min(base_elevations)
                wall.save(update_fields=['base_elevation_mm'])
                updated_count += 1
        else:
            # Wall not related to any room, set to 0
            if wall.base_elevation_mm != 0:
                wall.base_elevation_mm = 0
                wall.save(update_fields=['base_elevation_mm'])
                updated_count += 1
    
    print(f"Updated base_elevation_mm for {updated_count} wall(s)")
