# Generated by Django 5.1.4 on 2026-01-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_add_base_elevation_mm_to_wall'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall',
            name='base_elevation_manual',
            field=models.BooleanField(default=False, help_text='If True, base_elevation_mm was manually set by the user and should not be automatically updated based on room relationships.'),
        ),
    ]
