# Generated by Django 5.1.4 on 2026-01-14 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_add_base_elevation_manual_to_wall'),
    ]

    operations = [
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.FloatField(default=0.5, help_text='Horizontal position of window center relative to door width (0-1 ratio, 0.5 = center)')),
                ('position_y', models.FloatField(default=0.5, help_text='Vertical position of window center relative to door height (0-1 ratio, 0.5 = center)')),
                ('width', models.FloatField(help_text='Width of the window in mm')),
                ('height', models.FloatField(help_text='Height of the window in mm')),
                ('window_type', models.CharField(choices=[('glass', 'Glass'), ('panel', 'Panel'), ('louver', 'Louver')], default='glass', help_text='Type of window', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('door', models.ForeignKey(help_text='Door this window belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='core.door')),
            ],
            options={
                'ordering': ['position_y', 'position_x'],
            },
        ),
    ]
