# Generated by Django 5.1.4 on 2026-01-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='use_sloped_ceiling',
            field=models.BooleanField(default=True, help_text='If True, ceiling follows wall heights creating a sloped ceiling. If False, ceiling is flat at a single height (uses minimum wall height or room height).'),
        ),
    ]
