# Generated by Django 5.1.4 on 2026-01-16 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_add_use_sloped_ceiling_to_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='use_sloped_ceiling',
        ),
    ]
