# Generated by Django 5.1.4 on 2026-01-24 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_remove_room_use_sloped_ceiling'),
    ]

    operations = [
        migrations.CreateModel(
            name='WallWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.FloatField(default=0.5, help_text='Position along wall length (0-1 ratio, 0 = start, 1 = end, 0.5 = center)')),
                ('position_y', models.FloatField(default=0.5, help_text='Vertical position relative to wall height (0-1 ratio, 0 = bottom, 1 = top, 0.5 = center)')),
                ('width', models.FloatField(help_text='Width of the window in mm')),
                ('height', models.FloatField(help_text='Height of the window in mm')),
                ('window_type', models.CharField(choices=[('glass', 'Glass'), ('panel', 'Panel'), ('louver', 'Louver')], default='glass', help_text='Type of window', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wall', models.ForeignKey(help_text='Wall this window belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='core.wall')),
            ],
            options={
                'ordering': ['position_y', 'position_x'],
            },
        ),
    ]
