# Generated by Django 5.1.4 on 2026-02-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_add_wall_window_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorpanel',
            name='shape_data',
            field=models.JSONField(blank=True, help_text='List of {x,y} points defining the exact polygon shape for non-rectangular floor panels', null=True),
        ),
    ]
