# Generated by Django 5.1.4 on 2026-05-28 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_ceilingpanel_inner_face_material_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['list_order', '-updated_at', '-id']},
        ),
        migrations.AddField(
            model_name='project',
            name='list_order',
            field=models.PositiveIntegerField(default=0, help_text='Sort order within a folder (or uncategorized group).'),
        ),
        migrations.AddField(
            model_name='project',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.projectfolder'),
        ),
    ]
