# Generated by Django 5.1.4 on 2026-05-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_add_project_folders'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='exclude_from_ceiling',
            field=models.BooleanField(
                default=False,
                help_text='If True, skip ceiling plan generation for this room (e.g. open void, double-height space).',
            ),
        ),
    ]
