# Generated by Django 5.1.4 on 2026-06-15 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_room_temperature_range'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='')),
                ('position_x', models.FloatField(help_text='Text box anchor X in model mm')),
                ('position_y', models.FloatField(help_text='Text box anchor Y in model mm')),
                ('arrow_target_x', models.FloatField(blank=True, help_text='Arrow tip X in model mm; null means no arrow.', null=True)),
                ('arrow_target_y', models.FloatField(blank=True, help_text='Arrow tip Y in model mm; null means no arrow.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_annotations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_annotations', to='core.project')),
                ('storey', models.ForeignKey(help_text='Storey this annotation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='plan_annotations', to='core.storey')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
