/** In-app user manual. Button labels match the live UI. */

export const HELP_ROLE_OPTIONS = [
    { id: 'admin', label: 'Admin' },
    { id: 'drafter', label: 'Drafter' },
    { id: 'salesman', label: 'Salesman' },
    { id: 'guest', label: 'Guest' },
];

export const EDITOR_ROLES = ['admin', 'drafter'];
export const ALL_SIGNED_ROLES = ['admin', 'drafter', 'salesman'];

export function itemVisibleForRole(item, role) {
    if (!item?.roles || item.roles.length === 0) return true;
    return item.roles.includes(role);
}

export const MANUAL_GROUPS = [
    { id: 'start', title: 'Getting started' },
    { id: 'projects', title: 'Projects' },
    { id: 'draw', title: 'Drawing' },
    { id: 'rooms', title: 'Rooms, doors, levels' },
    { id: 'views', title: 'Ceiling, floor, 3D' },
    { id: 'output', title: 'Panels, export, share' },
    { id: 'ref', title: 'Shortcuts & tips' },
];

export const MANUAL_SECTIONS = [
    {
        id: 'intro',
        group: 'start',
        title: 'Introduction',
        keywords: 'overview units millimetres workflow cold store panel admin drafter salesman',
        blocks: [
            { type: 'p', roles: ['admin'], text: 'You are using an Admin account. You can draw projects, manage folders, share, review Comments, and open Accounts to create Drafter and Salesman users.' },
            { type: 'p', roles: ['drafter'], text: 'You are using a Drafter account. You can create and draw projects, generate panels, export, and review Comments. You cannot open Accounts (that is Admin only).' },
            { type: 'p', roles: ['salesman'], text: 'You are using a Salesman account. You only see projects an Admin or Drafter assigned to you. You cannot draw or generate. Use Feedback to leave notes, and 3D / Tour to walk the model.' },
            { type: 'p', roles: ['guest'], text: 'You are not signed in. Sign In with an Admin, Drafter, or Salesman account to use the system. Help still works here so you can read what each account can do — use the role buttons above.' },
            { type: 'img', roles: ['admin', 'drafter'], src: '/manual/05-wall-plan.png', alt: 'Wall plan workspace', caption: 'Admin and Drafter: Wall tab with Controls, dimension labels, and drawing after Enter Edit Mode.' },
            { type: 'img', roles: ['salesman', 'guest'], src: '/manual/02-home.png', alt: 'Home project list', caption: 'Salesman: Home lists only assigned projects. There is no Create New Project, New folder, or chat assistant.' },
            { type: 'p', text: 'All sizes are millimetres (mm) unless a field says otherwise. Temperature is °C. Installation rates are panels, doors, or slabs per day.' },
            { type: 'h3', roles: ['admin', 'drafter'], text: 'Typical order of work' },
            { type: 'steps', roles: ['admin', 'drafter'], items: [
                'Create or import a project (or use the chat assistant).',
                'On the Wall tab, Enter Edit Mode and draw walls.',
                'Click a corner to open Configure Joints (None / Butt-in / 45° Cut).',
                'Define Room, then Add Door / windows.',
                'Add extra storeys with Manage → Add Level if needed.',
                'Generate the Ceiling and Floor plans; set ceiling joints.',
                'Calculate Wall Panels, then open Summary & Install Time.',
                'Review 3D View / Tour, then Share or Export Project Report.',
            ] },
            { type: 'h3', roles: ['salesman'], text: 'Typical order of work' },
            { type: 'steps', roles: ['salesman'], items: [
                'Open Home. Banner: View-only access (Salesman). You only see assigned projects.',
                'Click a project row to open it.',
                'Review Wall, Ceiling, and Floor plans (zoom and pan only).',
                'Open 3D View and Tour to walk the model. Open or close doors with E or the Open Door button.',
                'Click Feedback. Optionally Select walls on plan, then Add comment.',
            ] },
            { type: 'h3', roles: ['guest'], text: 'Typical order of work' },
            { type: 'steps', roles: ['guest'], items: [
                'Ask an administrator for an account (Admin, Drafter, or Salesman).',
                'Sign In with Username and Password.',
                'Help then shows only the screens and buttons for that role.',
            ] },
            { type: 'note', roles: ['admin'], text: 'Only Admin sees Accounts in the top bar. Use it to add Drafter and Salesman users. Drafters get the same drawing tools as you; Salesmen get Feedback only.' },
            { type: 'note', roles: ['drafter'], text: 'You have the same drawing and export tools as Admin, except Accounts. Ask an Admin to create users or change roles.' },
            { type: 'note', roles: ['salesman'], text: 'Enter Edit Mode, Create New Project, Share, Plan notes, Generate Ceiling/Floor, and Accounts are hidden on a Salesman account. If a project is missing, ask an Admin or Drafter to assign it under Salesman visibility.' },
        ],
    },
    {
        id: 'login',
        group: 'start',
        title: 'Sign in, roles, and chrome',
        keywords: 'login password guest admin drafter salesman accounts theme dark light logout help',
        blocks: [
            { type: 'h3', text: 'Login' },
            { type: 'img', src: '/manual/01-login.png', alt: 'Sign in screen', caption: 'Sign in with Username and Password, or Continue as guest (view only). Help and theme are at the top right.' },
            { type: 'table', headers: ['Control', 'What it does'], rows: [
                ['Username / Password', 'Sign in with an account created by an administrator.'],
                ['Sign In', 'Opens the project list. Shows Signing in... while busy.'],
                ['Continue as guest (view only)', 'Browse without editing.'],
                ['Back to shared project (view only)', 'Return to a share link without signing in.'],
                ['Theme (sun / moon)', 'Switch to dark mode or Switch to light mode.'],
            ] },
            { type: 'note', text: 'Need an account? Contact your administrator to have one created. There is no public registration.' },
            { type: 'h3', text: 'Roles' },
            { type: 'table', headers: ['Role', 'Draw / edit', 'Comments', 'Other'], rows: [
                ['Admin', 'Yes', 'Comments', 'Accounts — create, edit, remove users'],
                ['Drafter', 'Yes', 'Comments', 'Full project editing'],
                ['Salesman', 'No', 'Feedback', 'Sees only assigned projects'],
                ['Guest / view-only share', 'No', 'No', 'Browse 2D and 3D'],
            ] },
            { type: 'h3', text: 'Top bar' },
            { type: 'table', headers: ['Control', 'What it does', 'Who sees it'], rows: [
                ['Help', 'Opens this manual. Content follows your role.', 'Everyone'],
                ['Theme toggle', 'Light or dark appearance.', 'Everyone'],
                ['Username + role badge', 'Admin, Drafter, or Salesman.', 'Signed in'],
                ['Accounts', 'Create / edit / remove users. Tabs Accounts (N) and Add account.', 'Admin only'],
                ['Logout', 'Sign out.', 'Signed in'],
                ['Login', 'Go to Sign In.', 'Guest'],
            ] },
        ],
    },
    {
        id: 'home',
        group: 'projects',
        title: 'Home, folders, and project list',
        keywords: 'home explorer folder search breadcrumb uncategorized delete rename visibility salesman',
        blocks: [
            { type: 'p', roles: ['admin', 'drafter'], text: 'Home is titled System V7.0. You see Create New Project (Create Project on small screens), New folder, and the chat assistant.' },
            { type: 'p', roles: ['salesman'], text: 'Home is titled System V7.0. Banner: View-only access (Salesman). You only see projects assigned to your account, and cannot create, rename, move, or delete.' },
            { type: 'p', roles: ['guest'], text: 'After you Sign In, Home lists projects. Admin and Drafter can create folders and projects. Salesman only sees assigned projects.' },
            { type: 'img', src: '/manual/02-home.png', alt: 'Home project explorer', caption: 'Folder tree on the left, project table on the right. Search is available to every signed-in role.' },
            { type: 'table', roles: ['admin', 'drafter'], headers: ['Control', 'What it does'], rows: [
                ['Create New Project / Create Project', 'Opens the create form.'],
                ['Projects breadcrumb', 'Jump to the top of the folder tree, or click a crumb to open that folder.'],
                ['Search projects...', 'Filter by name, folder, or dimensions. Clear with ×.'],
                ['New project here / New', 'Create a project in the current folder.'],
                ['New folder / New subfolder', 'Create a folder at this level, or inside the selected folder.'],
                ['Folder chevron', 'Expand or collapse child folders.'],
                ['Folder ⋯', 'New subfolder, Rename, Delete.'],
                ['Table columns', 'Name, Folder (while searching), Dimensions, Created by, Last edited by, Modified.'],
                ['Click a project row', 'Open the workspace.'],
                ['Visibility (people icon)', 'Salesman visibility — choose which salesman accounts can see this project.'],
                ['Pencil / Trash', 'Edit project or Delete project.'],
                ['Unread badge', 'Unread comments or feedback on that project.'],
                ['Open chat assistant', 'Guided create. Hidden for Salesman.'],
            ] },
            { type: 'table', roles: ['salesman'], headers: ['Control', 'What it does'], rows: [
                ['View-only access (Salesman) banner', 'Reminds you that you cannot create or edit.'],
                ['Projects breadcrumb', 'Jump folders you can see.'],
                ['Search projects...', 'Filter assigned projects. Clear with ×.'],
                ['Folder chevron', 'Expand or collapse child folders.'],
                ['Click a project row / Open', 'Open the project in view-only mode.'],
                ['Unread badge', 'Unread Feedback items you or others left.'],
            ] },
            { type: 'note', roles: ['salesman'], text: 'New project here, New folder, folder ⋯, pencil, trash, visibility, Create New Project, and the chat button are hidden. If a project is missing, ask an Admin or Drafter to tick your account in Salesman visibility.' },
            { type: 'p', roles: ['admin', 'drafter'], text: 'Special folder: Uncategorized. Empty states include No projects match your search, This folder is empty, and No projects here yet. CTA: New project in {folder}.' },
            { type: 'h3', roles: ['admin', 'drafter'], text: 'Create folder' },
            { type: 'p', roles: ['admin', 'drafter'], text: 'Create folder / Create subfolder → Folder name → Cancel or Create folder.' },
            { type: 'h3', roles: ['admin', 'drafter'], text: 'Edit project' },
            { type: 'p', roles: ['admin', 'drafter'], text: 'Edit Project: Project Name, Width (mm), Length (mm), Height (mm) → Cancel / Update Project. Wall thickness is set when you create the project, not here.' },
            { type: 'h3', roles: ['admin', 'drafter'], text: 'Salesman visibility' },
            { type: 'p', roles: ['admin', 'drafter'], text: 'Search salesman accounts... Lists: Can view this project and Not assigned. Cancel / Save. This is how a Salesman gets access to a project.' },
        ],
    },
    {
        id: 'create',
        group: 'projects',
        roles: ['admin', 'drafter'],
        title: 'Create a project',
        keywords: 'create new project width length height wall thickness import dwg pdf dxf folder',
        blocks: [
            { type: 'h3', text: 'Blank project' },
            { type: 'img', src: '/manual/03-create-project.png', alt: 'Create New Project form', caption: 'Project Name, Width / Length / Height (mm), Wall Thickness (mm), then Create Project. Import from DWG / PDF is below the form.' },
            { type: 'table', headers: ['Field', 'Notes'], rows: [
                ['Project Name', 'Required.'],
                ['Width (mm) / Length (mm) / Height (mm)', 'Site envelope for overall dimensions and 3D framing.'],
                ['Wall Thickness (mm)', 'Default thickness for new walls.'],
                ['Create Project', 'Creates the project, then Choose a folder if folders exist. Shows Creating... while busy.'],
            ] },
            { type: 'p', text: 'If you started from a folder, a banner shows This project will be added to {folder}. After create: pick a folder, Create a new folder / Create subfolder in…, or skip.' },
            { type: 'h3', text: 'Import from DWG / PDF' },
            { type: 'p', text: 'On the create form: or import from plan → Import from DWG / PDF (prefer DWG / DXF). Set PDF page if needed → Import plan.' },
            { type: 'p', text: 'From an existing project, Import plan from PDF / DWG reviews detected walls, doors, rooms, joints, height, and thickness, then Import into project.' },
            { type: 'note', text: 'Imported geometry is a starting point. Check snap, wall type, and room outlines before generating panels.' },
        ],
    },
    {
        id: 'chat',
        group: 'projects',
        roles: ['admin', 'drafter'],
        title: 'Chat assistant',
        keywords: 'chatbot fab create project folder rooms temperature floor ceiling joints',
        blocks: [
            { type: 'p', text: 'Editors see a chat button on the home page (Open chat assistant to create a project). It walks through folder, name, site size, wall thickness, rooms, then asks you to confirm. Say create to build, or restart to start over.' },
            { type: 'p', text: 'Examples: Help me create a project · Create a project and place it under folder Cold Stores · Help me create project Alpha, site 24m × 12m × 6m, under folder Clients.' },
            { type: 'table', headers: ['You can say', 'Meaning'], rows: [
                ['24m × 12m × 6m', 'Width × length × height. Small numbers without a unit are treated as metres.'],
                ['yes / no', 'Include rooms or skip.'],
                ['2 - 6', 'Temperature range in °C. ambient or default → 0 °C.'],
                ['same as previous', 'Copy remaining details from the last room.'],
                ['Slab / Panel / None', 'Floor type.'],
                ['PPGI / S/Steel / PVC', 'Face material.'],
                ['uncategorized', 'No folder.'],
            ] },
            { type: 'note', text: 'The assistant packs rooms so they share walls. It does not create ceiling joints — set those on the Ceiling tab after generation. Placeholder: Type your reply…' },
        ],
    },
    {
        id: 'workspace',
        group: 'draw',
        title: 'Project workspace',
        keywords: 'tabs wall ceiling floor summary 2d 3d undo redo share comments plan notes level manage',
        blocks: [
            { type: 'p', text: 'The header shows the project name and W × L × H mm.' },
            { type: 'note', roles: ['salesman'], text: 'The left Controls sidebar shows View-only mode instead of Enter Edit Mode. You can still switch Wall / Ceiling / Floor / 3D, export from Summary, and leave Feedback.' },
            { type: 'note', roles: ['guest'], text: 'On a view-only share link you can browse plans and 3D. Sign in as Admin or Drafter to edit, or as Salesman to leave Feedback on assigned projects.' },
            { type: 'img', src: '/manual/05-wall-plan.png', alt: 'Project workspace Wall tab', caption: 'Plan tabs and 2D / 3D are available to every signed-in role. Undo, Redo, Share, Plan notes, Manage, and Enter Edit Mode are Admin and Drafter only.' },
            { type: 'h3', text: 'Navigation' },
            { type: 'table', headers: ['Control', 'What it does'], rows: [
                ['Back to Projects / Projects', 'Return home (hidden on a share link).'],
                ['Top', 'Scroll to the top of the page.'],
                ['Show Controls', 'Restore the left Controls sidebar after it was collapsed.'],
                ['Collapse', 'Hide the Controls sidebar to give the canvas more width.'],
                ['2D View / 3D View', 'Switch between plan and 3D. 3D hides the plan tabs.'],
                ['Help', 'Opens this manual for your role.'],
            ] },
            { type: 'h3', text: 'Plan tabs (2D)' },
            { type: 'table', headers: ['Tab', 'When it is available'], rows: [
                ['Wall', 'Always.'],
                ['Ceiling', 'After at least one room exists.'],
                ['Floor', 'After rooms exist. May show (N) for panel-floor rooms. Title when disabled: Add rooms first.'],
                ['Summary & Install Time', 'Summary on small screens. Hidden on view-only share links.'],
            ] },
            { type: 'h3', roles: ['admin', 'drafter'], text: 'Header actions (Admin / Drafter)' },
            { type: 'table', roles: ['admin', 'drafter'], headers: ['Control', 'Notes'], rows: [
                ['Undo', 'Ctrl+Z'],
                ['Redo', 'Ctrl+Y'],
                ['Share', 'View-only or editable link. Not shown inside a share session.'],
                ['Comments', 'Review salesman Feedback. Unread badge.'],
                ['Plan notes', 'Wall tab only. Text boxes on the plan.'],
                ['Level dropdown', 'Active storey. No levels if none exist.'],
                ['Manage', 'Edit Level / Exit Edit Level, Add Level, Delete Level.'],
                ['Enter Edit Mode', 'Shows Drawing Tools.'],
            ] },
            { type: 'h3', roles: ['salesman'], text: 'Header actions (Salesman)' },
            { type: 'table', roles: ['salesman'], headers: ['Control', 'Notes'], rows: [
                ['Feedback', 'Opens Customer Feedback. You can Add comment and Select walls on plan.'],
                ['Level dropdown', 'Switch storey to review. You cannot Add Level or Delete Level.'],
                ['2D / 3D', 'Same as editors. Tour works.'],
            ] },
        ],
    },
    {
        id: 'zoom',
        group: 'draw',
        title: 'Zoom, pan, and dimension labels',
        keywords: 'zoom in zoom out reset pan right-click wheel overall wall dimensions panel lines purple blue orange',
        blocks: [
            { type: 'p', text: 'These controls sit on every 2D plan (Wall, Ceiling, Floor).' },
            { type: 'table', headers: ['Control', 'Desktop', 'Touch'], rows: [
                ['Zoom In / Zoom Out / Reset Zoom', 'Buttons on the canvas. Reset fits the plan.', 'Same buttons.'],
                ['Pan', 'Wall plan: right-click and drag. Ceiling / floor: left-drag.', 'Swipe sideways, or two-finger pan.'],
                ['Mouse wheel', 'Does not zoom the 2D plan — use the buttons.', '—'],
            ] },
            { type: 'p', text: 'Hint under the wall canvas: Click and drag to navigate · Use zoom buttons. Ceiling: Drag to pan · Use zoom buttons. Floor: Click panels to select · Drag to pan · Use zoom buttons.' },
            { type: 'h3', text: 'Dimension Labels (Wall plan)' },
            { type: 'table', headers: ['Checkbox', 'Colour', 'Meaning'], rows: [
                ['Overall project dimensions', 'Purple', 'Full site width and length.'],
                ['Wall dimensions', 'Blue', 'Length of each wall.'],
                ['Side Panel dimensions', 'Orange', 'Panel-module sizes along a wall.'],
                ['Panel division lines', '—', 'Seam lines (also Show Panel Lines in 3D).'],
            ] },
            { type: 'note', text: 'Crowded labels may hide rather than sit on the wrong wall. Project Dimensions Exceeded appears if drawing runs outside the site envelope.' },
        ],
    },
    {
        id: 'add-wall',
        group: 'draw',
        roles: ['admin', 'drafter'],
        title: 'Add Wall',
        keywords: 'add wall partition height thickness snap length finishes ppgi deduct auto-split',
        blocks: [
            { type: 'steps', items: [
                'Enter Edit Mode → Add Wall.',
                'Click the start point, then the end point.',
            ] },
            { type: 'img', src: '/manual/06-drawing-tools.png', alt: 'Drawing Tools in edit mode', caption: 'After Enter Edit Mode: Add Wall, Edit Wall, Merge Walls, Split Wall, Define Room, Add Door, Edit Door. Exit Edit Mode turns the tools off.' },
            { type: 'table', headers: ['Field', 'What it does'], rows: [
                ['Cancel', 'Leave Add Wall. Esc or right-click also cancels an unfinished wall.'],
                ['Wall Type', 'Wall or Partition.'],
                ['Height (mm) / Thickness (mm)', 'Wall size.'],
                ['Deduct new wall thickness from host at free corners', 'Shortens the host so the new wall sits flush.'],
                ['Auto-split walls at intersections', 'Cuts existing walls where the new wall crosses them.'],
                ['Face Finishes', 'Inner / Outer Material (PPGI, S/Steel, PVC) and Thickness (mm).'],
            ] },
            { type: 'p', text: 'Hint: Click on the canvas to start drawing. Click again to finish.' },
            { type: 'h3', text: 'Snap and length' },
            { type: 'ul', items: [
                'Endpoints snap to walls and intersections.',
                'Horizontal / vertical world snap is about 2°. Parallel / perpendicular to a slanted host tightens with length.',
                'A free (unsnapped) end opens Enter Wall Length. Type mm, then Confirm.',
                'Snap badges: World horizontal (90°), World vertical (90°), Perpendicular to slant (⊥), Along slant (∥), Free angle.',
                'Optional checkbox when tracing a PDF: Typed value is PDF horizontal/vertical span…',
            ] },
        ],
    },
    {
        id: 'edit-wall',
        group: 'draw',
        roles: ['admin', 'drafter'],
        title: 'Edit, merge, and split walls',
        keywords: 'edit wall lock length gap-fill windows merge confirm split distance joints ctrl-click',
        blocks: [
            { type: 'h3', text: 'Edit Wall' },
            { type: 'p', text: 'Edit Wall → click a wall. Tick Select Multiple Walls to click several. Show Edit Wall Form (N wall(s)) opens the editor. Header: Edit Wall Mode. Cancel editing with Cancel.' },
            { type: 'table', headers: ['Section', 'Controls'], rows: [
                ['Position & Dimensions', 'Start Point X/Y, End Point X/Y, Wall Length (mm). Padlock = Lock/Unlock Start X (and Y / End / length).'],
                ['Wall Properties', 'Wall Height (mm), Wall Base Elevation (mm), Wall Thickness (mm), Wall Type.'],
                ['Face Finishes', 'Inner / Outer material and sheet thickness. Outer face / Inner face.'],
                ['Advanced Options', 'Fill Gap Between Rooms → Enable Gap-Fill / ✓ Enabled. Gap-fill walls cannot host doors.'],
                ['Windows on Wall', 'Add Window, then Edit / Delete. Save the wall first if Add Window is disabled.'],
                ['Actions', 'Remove Wall (Delete wall?), Save, Cancel editing.'],
            ] },
            { type: 'p', text: 'Multi-select: Changes will be applied to all selected walls.' },
            { type: 'h3', text: 'Merge Walls' },
            { type: 'p', text: 'Merge Walls → click a run of walls that meet end-to-end and share type, height, thickness, and finishes → Confirm Merge. Success: Walls merged successfully!' },
            { type: 'h3', text: 'Split Wall' },
            { type: 'p', text: 'Split Wall → click the wall, then click the split point, or in Manual Wall Split type Distance from start (mm) and Split at Distance. Clear Selection drops the wall. Success: Wall split completed successfully!' },
            { type: 'h3', text: 'Show Plan Details (Wall)' },
            { type: 'ul', items: [
                'Show Plan Details / Collapse — material and elevation side panel.',
                'Wall Finish Legend — inner / outer face colours.',
                'View Material Needed → Show Material / Hide Material.',
                'Wall Elevations → Generate Elevations / Hide Elevations.',
                'Calculate Wall Panels — see Wall panel calculation.',
            ] },
        ],
    },
    {
        id: 'joints',
        group: 'draw',
        title: 'Wall joints (Configure Joints)',
        keywords: 'configure joints butt-in 45 cut none deduct thickness flip wall order intersection corner',
        blocks: [
            { type: 'p', roles: ['admin', 'drafter'], text: 'A joint is where two walls meet. After Enter Edit Mode, click a corner on the Wall plan to open Configure Joints. This is separate from Ceiling Joint Configuration (AA11 / Cut L / Cut 45).' },
            { type: 'note', roles: ['salesman'], text: 'Wall joints (Butt-in / 45° Cut) are set by Admin or Drafter in Enter Edit Mode. You cannot open Configure Joints. You still see the result in 2D, 3D, and export.' },
            { type: 'steps', roles: ['admin', 'drafter'], items: [
                'Enter Edit Mode. Leave Add Wall / Edit Wall / Define Room off — otherwise corners are used for those tools.',
                'Click a wall corner. Panel title: Configure Joints. Subtitle: N joints selected · click more on plan to add · Ctrl+click to remove.',
                'Pick a type per wall pair, then Save Changes. Cancel or × closes without saving.',
            ] },
            { type: 'table', roles: ['admin', 'drafter'], headers: ['Type', 'What it does'], rows: [
                ['None', 'No special cut. Default meeting.'],
                ['Butt-in', 'One wall butts into the other. Optional Deduct joining wall thickness — shortens Wall A by Wall B’s thickness. Hint: Shortens Wall {id} by Wall {id}\'s thickness.'],
                ['45° Cut', 'Miter / 45-degree cut at the corner.'],
            ] },
            { type: 'table', roles: ['admin', 'drafter'], headers: ['Control', 'What it does'], rows: [
                ['Click another corner', 'Add that joint to the panel.'],
                ['Ctrl+click (or Cmd+click) a corner', 'Remove that joint from the selection.'],
                ['Remove', 'Drop one joint when several are selected.'],
                ['Flip Wall Order', 'Swap which wall is Wall 1 vs Wall 2 (plan colours follow).'],
                ['Apply to all selected joints', 'When 2+ joints are selected: set None / Butt-in / 45° Cut, then Apply type to all N joints.'],
                ['Save Changes', 'Writes joints. Alert: Joint types updated! or Updated N joints.'],
                ['Cancel / ×', 'Close without saving.'],
            ] },
            { type: 'note', roles: ['admin', 'drafter'], text: 'Recalculate Wall Panels after you change joints. Ceiling joints (AA11 / Cut L / Cut 45) are on the Ceiling tab → select a room → Joint Configuration.' },
            { type: 'p', roles: ['guest'], text: 'Wall joints and ceiling joints are set by Admin or Drafter after they sign in and Enter Edit Mode.' },
        ],
    },
    {
        id: 'rooms',
        group: 'rooms',
        roles: ['admin', 'drafter'],
        title: 'Define Room and room form',
        keywords: 'define room polygon temperature height slab panel none base elevation variable walls',
        blocks: [
            { type: 'h3', text: 'Define Room' },
            { type: 'steps', items: [
                'Enter Edit Mode → Define Room.',
                'Click corners in order around the room. Points snap to wall ends and intersections.',
                'Click the first point again to close the loop.',
                'Fill in Create Room and click Create room.',
            ] },
            { type: 'p', text: 'Right-click undoes the last point. Esc cancels. Banner shows Points: and Walls: counts. Minimize → Drawing room area… then Restore panel, Resume form, or Cancel.' },
            { type: 'h3', text: 'Room form' },
            { type: 'table', headers: ['Field', 'Notes'], rows: [
                ['Room outline', 'Points (N) coordinates and Walls (N). While editing: click canvas corners in order around the perimeter, then save.'],
                ['Room name', 'e.g. Cold Room 1.'],
                ['Temperature (°C)', 'Single value or range, e.g. 5 or 2 - 6.'],
                ['Room height (mm)', '3000 or 5000-6000. Values ≤ 50 are treated as metres. Use minimum wall height (N mm) copies the shortest wall.'],
                ['Variable wall heights', 'Sloped roofs — room height will not rewrite wall heights.'],
                ['Base elevation (mm)', 'Floor height vs the storey datum. Chips −300, −150, 0, +150, +300.'],
                ['Floor Type', 'Slab, Panel, or None. Only Panel rooms are generated on the Floor tab.'],
                ['Floor Thickness / Layers', 'None or 50–200 mm; layers multiply total thickness.'],
                ['Notes', 'Optional remarks.'],
                ['Footer', 'Cancel, Delete (Delete room?), Create room / Save changes.'],
            ] },
            { type: 'h3', text: 'Room labels on the plan' },
            { type: 'p', text: 'Click the label to select. Double-click to edit Room Name, Height (mm), Description. Enter or click away saves; Esc cancels. Drag to move (disabled during Define Room). Title: Click to select room, double-click to edit.' },
        ],
    },
    {
        id: 'doors',
        group: 'rooms',
        roles: ['admin', 'drafter'],
        title: 'Doors and windows',
        keywords: 'add door edit door swing slide dock interior exterior window glass louver',
        blocks: [
            { type: 'p', text: 'Add Door → click the host wall (gap-fill walls are skipped). Edit Door → click an existing door symbol. The symbol sits on the interior (inner face) or exterior (outer face). Position is clamped so the full opening stays on the wall.' },
            { type: 'h3', text: 'Door form (Add New Door / Edit Door)' },
            { type: 'table', headers: ['Section', 'Controls'], rows: [
                ['Door Type & Configuration', 'Type: Swing, Slide, Dock Door. Configuration: Single-Sided / Double-Sided.'],
                ['Dimensions', 'Width, height, thickness (mm).'],
                ['Position on Wall', 'Slider; From Left to Door Edge (mm) and distance from the right.'],
                ['Side / direction', 'Interior or exterior. Swing / slide left or right. Dock doors do not use a swing/slide direction.'],
                ['Windows on Door', 'Add Window. Types: Glass / Panel / Louver.'],
                ['Actions', 'Cancel, Delete (Yes, Delete), Add Door / Update Door.'],
            ] },
            { type: 'p', text: 'In 3D View, select a door then Open Door / Close Door, or Space. In the tour, press E (or tap Open door / Close door on mobile).' },
            { type: 'h3', text: 'Windows on a wall' },
            { type: 'p', text: 'From Edit Wall → Add Window / Edit Window: Window Type Glass; Width / Height (mm); Position Along Wall (Distance from Left/Right); Position Height (Distance from Bottom/Top); Cancel / Save.' },
        ],
    },
    {
        id: 'levels',
        group: 'rooms',
        roles: ['admin', 'drafter'],
        title: 'Levels (storeys)',
        keywords: 'add level edit level delete storey elevation copy layout draw area',
        blocks: [
            { type: 'p', text: 'The level dropdown on the Wall tab sets which storey you are drawing. Each storey has its own walls, rooms, doors, and panels. Ground floor cannot be deleted.' },
            { type: 'h3', text: 'Add Level — Create New Storey' },
            { type: 'steps', items: [
                'Manage → Add Level.',
                'Step 1: Storey Name (e.g. First Floor). Copy Layout From: None or an existing storey.',
                'Step 2: Rooms to Copy Walls From. Custom Areas → Draw Area traces a polygon (same as Define Room). Remove deletes an area.',
                'Step 3: Name, Elevation (mm), Default Height, Included Rooms with Room Height (mm).',
                'Back, Cancel, Next, Create Storey.',
            ] },
            { type: 'p', text: 'While drawing a custom area: Drawing storey area… → Restore panel, Cancel drawing, Resume wizard. Esc cancels drawing.' },
            { type: 'h3', text: 'Edit Level Mode' },
            { type: 'p', text: 'Copy wall outlines from other levels onto the current storey. Clear Selection, Close / Exit Edit Level, room checkboxes, Base Elevation (mm), Room Height (mm), Add Selected Rooms. Status: Walls already copied to {level}.' },
            { type: 'h3', text: 'Delete Level' },
            { type: 'p', text: 'Confirm: Delete this level? Rooms, walls, and panels on this storey will be removed.' },
        ],
    },
    {
        id: 'notes',
        group: 'rooms',
        title: 'Plan notes, comments, and sharing',
        keywords: 'plan notes arrow delete feedback comments select walls share view only editable copy link',
        blocks: [
            { type: 'h3', roles: ['admin', 'drafter'], text: 'Plan notes (Wall tab)' },
            { type: 'table', roles: ['admin', 'drafter'], headers: ['Control', 'What it does'], rows: [
                ['Click the plan', 'Place a default text box.'],
                ['Drag on the plan', 'Draw a custom-size box.'],
                ['Add note / Done', 'Another note, or leave note mode.'],
                ['Selected note', 'Drag to move; Resize note box handle; double-click / Enter / F2 to edit (Type your note...).'],
                ['Arrow', 'Move arrow / Click plan for arrow tip — leader to a point on the plan.'],
                ['Delete (Del) / Backspace', 'Remove the note. Esc cancels text editing.'],
            ] },
            { type: 'h3', roles: ['admin', 'drafter'], text: 'Comments' },
            { type: 'p', roles: ['admin', 'drafter'], text: 'Open Comments. Panel title: Customer Feedback. Click a comment to highlight walls (Viewing walls referenced by a comment → Clear highlight). Close panel; minimized Restore panel / Back to comments.' },
            { type: 'h3', roles: ['salesman'], text: 'Feedback' },
            { type: 'p', roles: ['salesman'], text: 'Open Feedback. Panel title: Customer Feedback. Type in Enter customer feedback..., optionally Select walls on plan (Clear walls to drop them), then Add comment. You cannot edit the drawing from this panel.' },
            { type: 'note', roles: ['salesman'], text: 'Plan notes and Share are hidden on a Salesman account. Use Feedback so an Admin or Drafter can see your notes under Comments.' },
            { type: 'h3', roles: ['admin', 'drafter'], text: 'Share project' },
            { type: 'img', roles: ['admin', 'drafter'], src: '/manual/12-share.png', alt: 'Share project modal', caption: 'Access type View only or Editable, then Create view-only link / Create editable link. Recipients open this project only — not the project list.' },
            { type: 'p', roles: ['admin', 'drafter'], text: 'Access type: View only or Editable. Create view-only link / Create editable link. Share link + Copy (Copied). View-only links need no login. Editable links need an Admin or Drafter to Login to edit.' },
            { type: 'p', roles: ['guest'], text: 'On a view-only share link you can browse this project without signing in. You cannot open the project list or leave Feedback. On an editable share link, Login to edit with an Admin or Drafter account.' },
        ],
    },
    {
        id: '3d',
        group: 'views',
        title: '3D view and walkthrough tour',
        keywords: '3d interior exterior tour wasd space alt shift door fullscreen orbit pinch joystick',
        blocks: [
            { type: 'p', text: 'Click 3D View.' },
            { type: 'img', src: '/manual/08-3d-view.png', alt: '3D view toolbar', caption: 'Switch to Interior / Exterior, Tour, Hide Panel Lines / Show Panel Lines, and Fullscreen sit above the model. Drag to rotate.' },
            { type: 'h3', text: 'Orbit toolbar' },
            { type: 'table', headers: ['Control', 'What it does'], rows: [
                ['Switch to Interior / Switch to Exterior', 'Cutaway vs full shell. Mobile: Interior / Exterior.'],
                ['Tour / Exit Tour', 'Walkthrough. Title: Pick a starting point and walk the model.'],
                ['Show Panel Lines / Hide Panel Lines', 'Wall panel seams.'],
                ['Fullscreen / Exit Fullscreen', 'Enlarge the 3D view. Esc also exits.'],
                ['Open Door / Close Door', 'After you click a door. Disabled: No Door Selected. Space toggles.'],
            ] },
            { type: 'p', text: 'Orbit: left-drag rotate, right-drag pan, middle-drag or wheel dolly zoom, one finger rotate, two fingers pinch. Status: Drag to rotate · Pinch to zoom · Fullscreen…' },
            { type: 'h3', text: 'Start a tour' },
            { type: 'steps', items: [
                'Click Tour.',
                'Click the floor. HUD: Choose start — Click the floor to pick where your tour begins · Esc cancel.',
                'Start tour or Enter. Blocked: That spot is blocked. Click another point on the floor.',
            ] },
            { type: 'h3', text: 'Desktop tour' },
            { type: 'p', text: 'Click the model to capture the mouse. WASD or arrows walk, Shift sprint, Space fly up, Left Alt fly down, E open/close facing door, mouse look, scroll FOV zoom, Esc exit. Prompt: Open door (E) / Close door (E). You collide with walls; open doors are passages.' },
            { type: 'h3', text: 'Mobile tour' },
            { type: 'p', text: 'Left stick move (always run) · Right side look · FULL screen · Tap Open/Close door. ▲ fly up, ▼ fly down, FULL / EXIT fullscreen.' },
        ],
    },
    {
        id: 'ceiling',
        group: 'views',
        title: 'Ceiling plan',
        keywords: 'generate ceiling orientation joints aa11 cut l cut 45 nylon hanger alu suspension rails merge',
        blocks: [
            { type: 'p', text: 'Open the Ceiling tab after rooms exist. Header: Ceiling Plan / Project Ceiling Plan.' },
            { type: 'note', roles: ['salesman'], text: 'View-only access (Salesman). You can view ceiling plans, zoom, and export, but cannot generate, merge, set joints, or edit supports.' },
            { type: 'img', roles: ['admin', 'drafter'], src: '/manual/09-ceiling.png', alt: 'Ceiling plan generator', caption: 'Orientation Strategy, panel Width / Length, thickness and face materials, then Generate Ceiling Plan or Merge Ceilings.' },
            { type: 'img', roles: ['salesman', 'guest'], src: '/manual/09-ceiling.png', alt: 'Ceiling plan', caption: 'Salesman: review the generated ceiling. Generate Ceiling Plan, Merge Ceilings, joints, and Support Tools are hidden or disabled.' },
            { type: 'h3', roles: ['admin', 'drafter'], text: 'Generation' },
            { type: 'table', roles: ['admin', 'drafter'], headers: ['Control', 'What it does'], rows: [
                ['Level: / View:', 'Storey, or All Rooms vs one room ((no ceiling) if excluded).'],
                ['Orientation Strategy', 'Auto (Recommended); All Vertical (Up/Down); All Horizontal (Left/Right); Room Optimal (Best per room).'],
                ['Panel Dimensions', 'Width; Length Auto or custom.'],
                ['Ceiling Settings', 'Thickness; Inner / Outer Material (PPGI, S/Steel, Aluminium, PVC) and sheet thickness.'],
                ['Generate Ceiling Plan', 'Builds panels. Regenerates after changes. Generating... while busy.'],
                ['Merge Ceilings / Close Merge Mode', 'Combine rooms. Merge Selected Rooms; Existing Merged Zones can be unmerged. Internal walls of a merged zone are AA11.'],
            ] },
            { type: 'h3', text: 'Joint Configuration (ceiling)' },
            { type: 'p', roles: ['admin', 'drafter'], text: 'Select a room (or merged zone). Tabs: Room Details | Joint Configuration. This is how the ceiling meets each wall — not the same as Wall-plan Configure Joints (Butt-in / 45° Cut).' },
            { type: 'p', roles: ['salesman'], text: 'Select a room, then Joint Configuration. You can read AA11 / Cut L / Cut 45. Joint Type dropdowns, Set All, and Save Now are disabled.' },
            { type: 'table', headers: ['Joint', 'Meaning'], rows: [
                ['Not Set', 'No ceiling joint type stored yet.'],
                ['AA11', 'No cutting at that wall. Auto-adjustment: wall height becomes room height minus ceiling thickness.'],
                ['Cut L', 'L-shaped cut. Set Horizontal Extension (mm) (default follows wall thickness). Vertical depth = ceiling thickness. Reset restores the default.'],
                ['Cut 45', '45-degree cut marker. No automatic height calculations.'],
            ] },
            { type: 'p', roles: ['admin', 'drafter'], text: 'Quick actions: Set All AA11, Set All Cut L (Default), Clear All. Save Now. Configurations are saved automatically when you generate the ceiling plan. Shared walls show Shared (N rooms) and may be Controlled by: {taller room}. Internal walls of a merged zone are AA11. Apply Settings to this room only / this zone only.' },
            { type: 'note', roles: ['admin', 'drafter'], text: 'Joint configurations saved successfully! appears after Save Now. Then Generate Ceiling Plan (or Regenerate) so panels match.' },
            { type: 'h3', roles: ['admin', 'drafter'], text: 'Support Tools' },
            { type: 'p', roles: ['admin', 'drafter'], text: 'Show Support Tools. Auto nylon on long panels (threshold 6000 mm, or 3000 mm if thickness ≤ 100 mm). Include accessories / Include cable. Alu suspension (draw rails on canvas). Add nylon hanger (manual) / Cancel add nylon. Draw support line / Cancel draw rail (snaps H/V). Clear all supports.' },
            { type: 'p', roles: ['admin', 'drafter'], text: 'Click a red hanger or purple rail to edit offsets, then Done or Delete hanger / Delete rail. Esc deselects. Delete / Backspace deletes. Enter applies an offset field.' },
            { type: 'h3', text: 'Plan Details' },
            { type: 'p', text: 'Show Plan Details: Total / Full / Cut panels, waste %, orientation, support Needed / Not Needed, Ceiling Panel Finish Legend. Dimension Legend: Overall outline (blue), Panel Dimensions (grey), Cut Dimensions (red). Also Walls (Outer Face) / Walls (Inner Face).' },
        ],
    },
    {
        id: 'floor',
        group: 'views',
        title: 'Floor plan',
        keywords: 'generate floor slab size panel dimensions waste orientation',
        blocks: [
            { type: 'p', text: 'Open the Floor tab. Only rooms whose floor type is Panel are generated. There is no wall drawing on this tab.' },
            { type: 'note', roles: ['salesman'], text: 'You can view a generated floor plan and zoom. Generate Floor Plan and panel settings are disabled on a Salesman account.' },
            { type: 'img', roles: ['admin', 'drafter'], src: '/manual/10-floor.png', alt: 'Floor plan generator', caption: 'Room dimensions / Panel dimensions checkboxes, Orientation, panel Width / Length, then Generate Floor Plan.' },
            { type: 'img', roles: ['salesman', 'guest'], src: '/manual/10-floor.png', alt: 'Floor plan', caption: 'Salesman: review panel floors that an editor already generated.' },
            { type: 'table', roles: ['admin', 'drafter'], headers: ['Control', 'What it does'], rows: [
                ['Level:', 'Storey filter.'],
                ['Room dimensions / Panel dimensions', 'Label toggles.'],
                ['Orientation', 'Auto / All Horizontal / All Vertical / Room Optimal.'],
                ['Panel Dimensions', 'Width; Length Auto or custom.'],
                ['Generate Floor Plan', 'Builds floor panels.'],
                ['Show Plan Details', 'Stats and legend.'],
                ['Slab size (mm) Width × Length', 'Defaults 1210 × 3000. Slab Floor Summary (N slabs needed) for slab take-off.'],
                ['Floor Panel List', 'Show Panel Table / Hide Panel Table.'],
            ] },
            { type: 'table', roles: ['salesman'], headers: ['Control', 'What it does'], rows: [
                ['Level:', 'Switch storey to review.'],
                ['Room dimensions / Panel dimensions', 'Label toggles (if the plan was generated).'],
                ['Show Plan Details', 'Stats and legend. You cannot generate or change layout.'],
                ['Zoom In / Out / Reset', 'Same as other 2D plans.'],
            ] },
            { type: 'p', text: 'Dimension Legend matches the ceiling: Overall outline, Panel Dimensions, Cut Dimensions, plus Slab Floor Calculations and wall inner/outer faces.' },
        ],
    },
    {
        id: 'panels',
        group: 'output',
        roles: ['admin', 'drafter'],
        title: 'Wall panel calculation',
        keywords: 'calculate wall panels optimized default leftover material analysis refresh walls',
        blocks: [
            { type: 'p', text: 'On the Wall tab Plan Details:' },
            { type: 'table', headers: ['Control', 'What it does'], rows: [
                ['Calculate Wall Panels (Optimized)', 'Searches cutting orders to reduce waste.'],
                ['Calculate Wall Panels (Default)', 'Straightforward cut list.'],
                ['Try Optimized Method / Try Default Method', 'Switch strategy, then calculate again.'],
                ['Show Panel Table / Hide Panel Table', 'Full / cut / leftover rows.'],
                ['Refresh Walls', 'Reload walls from all levels/storeys.'],
                ['Material Analysis', 'Full, cut, leftover panels; doors needed. Leftover details: factory joint remaining, usable for, face finishes.'],
            ] },
            { type: 'note', text: 'Recalculate after you change walls, joints, doors, or storeys. Stale results are flagged when the wall layout has changed.' },
        ],
    },
    {
        id: 'export',
        group: 'output',
        title: 'Summary, installation time, and export',
        keywords: 'export project report excel pdf elevations panels per day working days fetch data',
        blocks: [
            { type: 'p', text: 'Summary & Install Time tab. Title: Project Summary & Installation Time Estimator. Hidden on view-only share links.' },
            { type: 'img', src: '/manual/11-summary.png', alt: 'Summary and installation estimator', caption: 'Export Project Report, Refresh Data, Fetch Data & Images, room/wall/door counts, and Panels / Doors / Slabs per Day.' },
            { type: 'table', headers: ['Control', 'What it does'], rows: [
                ['Export Project Report', 'Opens Export Preview (Preparing / Capturing / Auto-Fetching).'],
                ['Refresh Data', 'Reload counts from all storeys.'],
                ['Fetch Data & Images', 'Capture Wall / Ceiling / Floor Plan images. Overlay: Auto-Fetching Data & Images / Success!'],
                ['Panels per Day / Doors per Day / Slabs per Day', 'Crew rates.'],
                ['Working Days', 'Includes a 20% buffer; also weeks and months.'],
                ['Page Orientation', 'Portrait or Landscape.'],
                ['Front Elevation / Side Elevation', 'Include building elevations.'],
                ['Download Excel', 'Spreadsheet take-off.'],
                ['Generate & Download PDF', 'Printable report with plans and tables.'],
            ] },
            { type: 'note', roles: ['admin', 'drafter'], text: 'If panels are missing, generate ceiling and floor plans first, then Calculate Wall Panels.' },
            { type: 'note', roles: ['salesman'], text: 'You can export. You cannot generate missing ceiling or floor panels — ask an Admin or Drafter if the report is empty.' },
        ],
    },
    {
        id: 'shortcuts',
        group: 'ref',
        title: 'Keyboard shortcuts',
        keywords: 'ctrl z y esc delete backspace wasd shift space alt enter f2',
        blocks: [
            { type: 'h3', roles: ['admin', 'drafter'], text: 'Everywhere (Admin / Drafter)' },
            { type: 'table', roles: ['admin', 'drafter'], headers: ['Shortcut', 'Action'], rows: [
                ['Ctrl+Z / Ctrl+Y', 'Undo / Redo.'],
                ['Esc', 'Cancel drawing, close a tool, exit tour placement, deselect a ceiling support, or exit 3D fullscreen.'],
                ['Help (top bar)', 'Open this manual for your role.'],
            ] },
            { type: 'h3', roles: ['salesman', 'guest'], text: 'Everywhere' },
            { type: 'table', roles: ['salesman', 'guest'], headers: ['Shortcut', 'Action'], rows: [
                ['Esc', 'Close Help, exit tour placement, or exit 3D fullscreen.'],
                ['Help (top bar)', 'Open this manual. Content matches the selected role.'],
            ] },
            { type: 'h3', roles: ['admin', 'drafter'], text: 'Wall plan' },
            { type: 'table', roles: ['admin', 'drafter'], headers: ['Shortcut / gesture', 'Action'], rows: [
                ['Left-click', 'Draw, select, place.'],
                ['Right-click + drag', 'Pan.'],
                ['Right-click while drawing a wall', 'Cancel the wall.'],
                ['Right-click in Define Room', 'Undo last point.'],
                ['Ctrl+click on a joint', 'Remove from multi-select (Configure Joints).'],
                ['Enter / F2', 'Edit a selected plan note.'],
                ['Delete / Backspace', 'Delete selected note, nylon hanger, or rail.'],
            ] },
            { type: 'h3', roles: ['salesman'], text: 'Wall plan (view only)' },
            { type: 'table', roles: ['salesman'], headers: ['Shortcut / gesture', 'Action'], rows: [
                ['Right-click + drag', 'Pan the wall plan.'],
                ['Zoom In / Out / Reset Zoom', 'Fit and inspect the plan.'],
            ] },
            { type: 'h3', text: '3D tour' },
            { type: 'table', headers: ['Key', 'Action'], rows: [
                ['W A S D / arrows', 'Walk.'],
                ['Shift', 'Sprint.'],
                ['Space / Left Alt', 'Fly up / fly down.'],
                ['E', 'Open or close the facing door.'],
                ['Esc', 'Exit tour.'],
                ['Space (orbit, door selected)', 'Toggle door.'],
            ] },
        ],
    },
    {
        id: 'tips',
        group: 'ref',
        title: 'Tips and troubleshooting',
        keywords: 'grey tabs database invalid project salesman joints purple dimensions tour blocked',
        blocks: [
            { type: 'ul', roles: ['admin', 'drafter'], items: [
                'Draw walls before rooms. Define Room needs a closed loop on existing walls.',
                'Ceiling and Floor tabs stay grey until at least one room exists. Hover Floor when disabled: Add rooms first.',
                'No Ceiling Plan Generated / No Floor Plan Generated: click Generate Ceiling Plan / Generate Floor Plan.',
                'Floor generation only includes rooms with floor type Panel. Use Slab for slab take-off on Floor Plan Details, not panel layout.',
                'Recalculate wall panels after any wall, door, or joint change.',
                'If overall purple dimensions look wrong, drawing may extend outside the project width × length. Enlarge the project in Edit project, or pull walls back inside. Message: Project Dimensions Exceeded.',
                'Tour start must be on a floor inside a room, not inside a wall. That spot is blocked. Click another point on the floor.',
                'Undo / Redo stay disabled until you make an edit in this session.',
                'Gap-fill walls cannot host doors. Add Door skips them.',
                'Ground floor cannot be deleted.',
                'Editable share links cannot edit until an Admin or Drafter signs in (Login to edit). View-only share: no login, no project list.',
                'The chat assistant will not set ceiling joints. Open Joint Configuration after generation.',
                'Database connection failed means the API is not reachable. Start the Django server and refresh.',
                'Invalid Project → Go to Projects if the URL id is wrong.',
            ] },
            { type: 'ul', roles: ['salesman'], items: [
                'Home only lists projects assigned under Salesman visibility. If a project is missing, ask an Admin or Drafter to tick your account.',
                'Banner: View-only access (Salesman). You can navigate tabs, view 3D, export, and leave Feedback — you cannot edit walls, rooms, levels, or plans.',
                'Ceiling and Floor tabs stay grey until an editor has defined at least one room.',
                'If No Ceiling Plan Generated / No Floor Plan Generated, ask an editor to generate. You cannot Generate Ceiling Plan or Generate Floor Plan.',
                'Tour start must be on a floor inside a room, not inside a wall. That spot is blocked. Click another point on the floor.',
                'Use Feedback (not Plan notes). Optionally Select walls on plan so the editor can jump to them from Comments.',
                'Database connection failed means the API is not reachable. Refresh or ask an administrator.',
                'Invalid Project → Go to Projects if the URL id is wrong.',
            ] },
            { type: 'ul', roles: ['guest'], items: [
                'Need an account? Ask an administrator. There is no public registration.',
                'Sign In to use Home. Continue as guest (view only) does not open the project list.',
                'Use a view-only share link to browse one project without logging in.',
                'Editable share links show Login to edit — only Admin or Drafter can draw.',
            ] },
            { type: 'h3', text: 'What you see in each situation' },
            { type: 'table', headers: ['Situation', 'What happens', 'What to do'], rows: [
                ['Not signed in', 'Protected pages send you to Sign In.', 'Sign In, or Continue as guest (view only) — guest still cannot open / without an account because the home route is protected. Use a share link to browse a project without login.'],
                ['Admin', 'Enter Edit Mode, drawing tools, Share, Comments, and Accounts.', 'Draw, generate, export, manage users.'],
                ['Drafter', 'Same drawing tools as Admin. No Accounts.', 'Draw, generate, export, review Comments.'],
                ['Salesman', 'Banner: View-only access (Salesman)… Drawing tools hidden.', 'Open assigned projects, use Feedback, orbit 3D, export.'],
                ['View-only share', 'Badge View-only link. No Back to Projects. No edit.', 'Browse plans and 3D. Cannot change the model.'],
                ['Editable share, logged out', 'Badge Editable link. Login to edit.', 'Sign in as Admin or Drafter to draw.'],
                ['No rooms yet', 'Ceiling and Floor tabs disabled.', 'Admin / Drafter: Enter Edit Mode → Define Room first.'],
                ['Rooms exist, no panels yet', 'Ceiling / Floor show generate forms (editors).', 'Admin / Drafter: Generate Ceiling Plan / Generate Floor Plan.'],
                ['Sidebar collapsed', 'Show Controls appears; drawing tools hidden.', 'Click Show Controls, then Enter Edit Mode (editors).'],
            ] },
        ],
    },
];

export function sectionsForRole(role) {
    const viewRole = HELP_ROLE_OPTIONS.some((option) => option.id === role) ? role : 'guest';
    return MANUAL_SECTIONS
        .filter((section) => itemVisibleForRole(section, viewRole))
        .map((section) => ({
            ...section,
            blocks: (section.blocks || []).filter((block) => itemVisibleForRole(block, viewRole)),
        }))
        .filter((section) => section.blocks.length > 0);
}

export function searchManualSections(query, role) {
    const sections = sectionsForRole(role);
    const q = String(query || '').trim().toLowerCase();
    if (!q) return sections;
    return sections.filter((section) => {
        const hay = [
            section.title,
            section.keywords,
            ...section.blocks.flatMap((block) => {
                if (block.text) return [block.text];
                if (block.items) return block.items;
                if (block.rows) return block.rows.flat();
                if (block.headers) return block.headers;
                if (block.type === 'img') return [block.alt, block.caption, block.src];
                return [];
            }),
        ].join(' ').toLowerCase();
        return hay.includes(q);
    });
}

