/** In-app user manual. Wrap UI labels in **bold**. Labels match the live UI. */

export const HELP_ROLE_OPTIONS = [
    { id: 'admin', label: 'Admin' },
    { id: 'drafter', label: 'Drafter' },
    { id: 'salesman', label: 'Salesman' },
    { id: 'guest', label: 'Guest' },
];

export const EDITOR_ROLES = ['admin', 'drafter'];
export const ALL_SIGNED_ROLES = ['admin', 'drafter', 'salesman'];

export function itemVisibleForRole(item, role) {
    if (!item?.roles || item.roles.length === 0) return true;
    return item.roles.includes(role);
}

export const MANUAL_GROUPS = [
    { id: 'start', title: 'Getting started' },
    { id: 'projects', title: 'Projects' },
    { id: 'draw', title: 'Drawing' },
    { id: 'rooms', title: 'Rooms, doors, levels' },
    { id: 'views', title: 'Ceiling, floor, 3D' },
    { id: 'output', title: 'Panels, export, share' },
    { id: 'ref', title: 'Shortcuts & tips' },
];

export const MANUAL_SECTIONS = [
    {
        id: 'intro',
        group: 'start',
        title: 'Introduction',
        keywords: 'overview units millimetres workflow cold store panel admin drafter salesman',
        blocks: [
            { type: 'p', roles: ['admin'], text: 'You are signed in as Admin. You can draw projects, manage folders, share, review **Comments**, and open **Accounts** to create Drafter and Salesman users.' },
            { type: 'p', roles: ['drafter'], text: 'You are signed in as Drafter. You can create and draw projects, generate panels, export, and review **Comments**. **Accounts** is Admin only.' },
            { type: 'p', roles: ['salesman'], text: 'You are signed in as Salesman. You only see projects assigned to you. You cannot draw or generate. Use **Feedback** for notes, and **3D** or **Tour** to walk the model.' },
            { type: 'p', roles: ['guest'], text: 'You are not signed in. Use the username and password your administrator gave you. After you sign in, Help shows only the screens for your account.' },
            { type: 'img', roles: ['admin', 'drafter'], src: '/manual/05-wall-plan.png', alt: 'Wall plan workspace', caption: 'Wall tab after **Enter Edit Mode**, with Controls and dimension labels.' },
            { type: 'img', roles: ['salesman'], src: '/manual/02-home.png', alt: 'Home project list', caption: 'Home lists only the projects assigned to you.' },
            { type: 'img', roles: ['guest'], src: '/manual/01-login.png', alt: 'Sign in screen', caption: 'Sign in with **Username** and **Password**.' },
            { type: 'p', text: 'Sizes are millimetres (mm) unless a field says otherwise. Temperature is °C. Installation rates are panels, doors, or slabs per day.' },
            { type: 'h3', roles: ['admin', 'drafter'], text: 'Typical order of work' },
            { type: 'steps', roles: ['admin', 'drafter'], items: [
                'On Home, click **Create New Project**.',
                'Enter the name, site size, and wall thickness, then click **Create Project**.',
                'On the **Wall** tab, click **Show Controls** if the sidebar is hidden.',
                'Click **Enter Edit Mode**, then **Add Wall**. Draw a closed outline.',
                'Click **Exit Edit Mode**, then click each corner to set joints. Save.',
                'Enter Edit Mode again. Use **Define Room**, then **Add Door**.',
                'If you need another storey, use **Manage** → **Add Level**.',
                'On **Ceiling**, set joints, then click **Generate Ceiling Plan**.',
                'On **Floor**, generate panel floors. Use **Slab size** for slab take-off.',
                'On **Wall**, open **Show Plan Details** and calculate wall panels.',
                'Open **Summary & Install Time** to export Excel or PDF.',
                'Use **3D View** or **Tour** to check the model. **Share** sends a link.',
            ] },
            { type: 'h3', roles: ['salesman'], text: 'Typical order of work' },
            { type: 'steps', roles: ['salesman'], items: [
                'Sign in. Home shows only projects assigned to you.',
                'Search or open a folder, then click a project.',
                'Review **Wall**, **Ceiling**, and **Floor**. Grey tabs mean the plan is not ready yet.',
                'Click **3D View** to orbit, or **Tour** to walk inside (WASD, **E** for doors).',
                'Open **Summary & Install Time** to read counts and export.',
                'Click **Feedback** to leave a note. Use **Select walls on plan** if you want to point at walls.',
                'Click **Back to Projects** when you are done.',
            ] },
            { type: 'h3', roles: ['guest'], text: 'Typical order of work' },
            { type: 'steps', roles: ['guest'], items: [
                'Ask an administrator for an account. There is no public registration.',
                'Type **Username** and **Password**, then click **Sign In**.',
                'If you have a share link, open that URL to browse one project without signing in.',
            ] },
            { type: 'note', roles: ['admin'], text: 'Only Admin sees **Accounts**. Drafters get the same drawing tools. Salesmen get **Feedback** only.' },
            { type: 'note', roles: ['drafter'], text: 'You have the same drawing and export tools as Admin, except **Accounts**.' },
            { type: 'note', roles: ['salesman'], text: 'You cannot create or edit projects. If a project is missing, ask an administrator to assign it to you.' },
        ],
    },
    {
        id: 'login',
        group: 'start',
        title: 'Sign in',
        keywords: 'login password guest admin drafter salesman accounts theme dark light logout help',
        blocks: [
            { type: 'img', src: '/manual/01-login.png', alt: 'Sign in screen', caption: '**Username**, **Password**, and **Sign In**. Help and theme are at the top right.' },
            { type: 'steps', items: [
                'Type your **Username**, then **Password**.',
                'Click **Sign In**. Home opens when it succeeds.',
                'If it fails, check spelling and ask an administrator to confirm the account.',
            ] },
            { type: 'table', headers: ['Control', 'What it does'], rows: [
                ['Sign In', 'Opens the project list.'],
                ['Continue as guest (view only)', 'Does not open Home. Use a share link, or sign in.'],
                ['Back to shared project (view only)', 'Returns to a share link without signing in.'],
                ['Theme (sun / moon)', 'Light or dark appearance.'],
            ] },
            { type: 'note', text: 'Need an account? Ask an administrator. There is no public registration.' },
            { type: 'h3', roles: ['admin'], text: 'Roles' },
            { type: 'table', roles: ['admin'], headers: ['Role', 'Draw / edit', 'Notes'], rows: [
                ['Admin', 'Yes', '**Accounts**, **Comments**, full drawing'],
                ['Drafter', 'Yes', '**Comments**, full drawing. No **Accounts**'],
                ['Salesman', 'No', '**Feedback**. Assigned projects only'],
                ['Guest / share link', 'No', 'Browse 2D and 3D'],
            ] },
            { type: 'h3', text: 'Top bar' },
            { type: 'table', roles: ['admin'], headers: ['Control', 'What it does'], rows: [
                ['Help', 'Opens this manual.'],
                ['Accounts', 'Create, edit, or remove Drafter and Salesman users.'],
                ['Logout', 'Sign out.'],
            ] },
            { type: 'table', roles: ['drafter'], headers: ['Control', 'What it does'], rows: [
                ['Help', 'Opens this manual.'],
                ['Logout', 'Sign out.'],
            ] },
            { type: 'table', roles: ['salesman'], headers: ['Control', 'What it does'], rows: [
                ['Help', 'Opens this manual.'],
                ['Logout', 'Sign out.'],
            ] },
            { type: 'table', roles: ['guest'], headers: ['Control', 'What it does'], rows: [
                ['Help', 'Opens this login Help.'],
                ['Login / Sign In', 'Go to the sign-in form.'],
            ] },
        ],
    },
    {
        id: 'accounts',
        group: 'start',
        roles: ['admin'],
        title: 'Accounts',
        keywords: 'accounts add account create user drafter salesman password role remove',
        blocks: [
            { type: 'p', text: 'Only Admin sees **Accounts**. Use it to create Drafter and Salesman users, change a role, reset a password, or remove an account.' },
            { type: 'h3', text: 'Create an account' },
            { type: 'steps', items: [
                'Click **Accounts** in the top bar.',
                'Open the **Add account** tab.',
                'Enter a username and a password (at least 6 characters).',
                'Set the role to **Drafter** or **Salesman**. You cannot create another Admin here.',
                'Click **Create account**. Give the person their username and password.',
            ] },
            { type: 'h3', text: 'Edit or remove' },
            { type: 'steps', items: [
                'On **Accounts**, filter with All, Admin, Drafter, or Salesman if the list is long.',
                'Change a role and save, or open edit to set a new password.',
                'Remove asks for confirmation. That cannot be undone from this dialog.',
            ] },
            { type: 'note', text: 'A Salesman still cannot see a project until you open **Visibility** on Home, tick their account, and click **Save**.' },
        ],
    },
    {
        id: 'home',
        group: 'projects',
        roles: ['admin', 'drafter', 'salesman'],
        title: 'Home and folders',
        keywords: 'home explorer folder search breadcrumb uncategorized delete rename visibility salesman',
        blocks: [
            { type: 'p', roles: ['admin', 'drafter'], text: 'Home is titled **System V7.0**. Folders are on the left. Projects are in the table on the right.' },
            { type: 'p', roles: ['salesman'], text: 'Home is titled **System V7.0**. The banner **View-only access (Salesman)** means you cannot create or edit. You only see assigned projects.' },
            { type: 'img', roles: ['admin', 'drafter'], src: '/manual/02-home.png', alt: 'Home project explorer', caption: 'Folder tree on the left, project table on the right.' },
            { type: 'img', roles: ['salesman'], src: '/manual/02-home.png', alt: 'Home project list', caption: 'Search and open assigned projects. Create and folders are hidden.' },
            { type: 'h3', roles: ['admin', 'drafter'], text: 'Open a project' },
            { type: 'steps', roles: ['admin', 'drafter'], items: [
                'Click a folder on the left. Use the chevron to expand subfolders.',
                'Click a project row to open the Wall workspace.',
                'To move a project, drag its row onto a folder.',
            ] },
            { type: 'h3', roles: ['salesman'], text: 'Open a project' },
            { type: 'steps', roles: ['salesman'], items: [
                'Optionally type in **Search projects...**. Click × to clear.',
                'Click a folder if the tree is shown, then click the project row (or **Open**).',
                'If a project is missing, ask an administrator to assign it to you.',
            ] },
            { type: 'h3', roles: ['admin', 'drafter'], text: 'Create a folder' },
            { type: 'steps', roles: ['admin', 'drafter'], items: [
                'Click **New folder**, or folder **⋯** → **New subfolder**.',
                'Type the folder name.',
                'Click **Create folder**.',
            ] },
            { type: 'h3', roles: ['admin', 'drafter'], text: 'Edit a project name or size' },
            { type: 'steps', roles: ['admin', 'drafter'], items: [
                'On the project row, click the pencil.',
                'Change the name, width, length, or height.',
                'Click **Update Project**. Wall thickness is set when you create the project, not here.',
            ] },
            { type: 'h3', roles: ['admin', 'drafter'], text: 'Delete a project or folder' },
            { type: 'steps', roles: ['admin', 'drafter'], items: [
                'On a project row, click Trash (**Delete project**), then confirm.',
                'On a folder, click **⋯** → **Delete**.',
                'Confirm **Delete Folder**. Projects inside move to **Uncategorized**.',
            ] },
            { type: 'h3', roles: ['admin', 'drafter'], text: 'Let a Salesman see this project' },
            { type: 'steps', roles: ['admin', 'drafter'], items: [
                'On the project row, click **Visibility** (people icon).',
                'Move accounts between **Can view this project** and **Not assigned**.',
                'Click **Save**.',
            ] },
            { type: 'note', roles: ['admin', 'drafter'], text: 'Empty folders can show **This folder is empty** or **New project in {folder}**. Projects with no folder sit in **Uncategorized**.' },
        ],
    },
    {
        id: 'create',
        group: 'projects',
        roles: ['admin', 'drafter'],
        title: 'Create a project',
        keywords: 'create new project width length height wall thickness import dwg pdf dxf folder',
        blocks: [
            { type: 'img', src: '/manual/03-create-project.png', alt: 'Create New Project form', caption: 'Name, site size, wall thickness, then **Create Project**.' },
            { type: 'h3', text: 'Blank project' },
            { type: 'steps', items: [
                'On Home, click **Create New Project**.',
                'Type the **Project Name**.',
                'Enter width, length, and height (mm). These set the site envelope.',
                'Enter **Wall Thickness (mm)**. New walls use this default.',
                'Click **Create Project**.',
                'If folders exist, pick one, create a new folder, or skip.',
            ] },
            { type: 'h3', text: 'Import from DWG / PDF' },
            { type: 'steps', items: [
                'On the create form, scroll to **or import from plan**.',
                'Prefer DWG or DXF. For a PDF, set the page if it is not page 1.',
                'Enter the project name above, then click **Import plan**.',
                'Review the detected walls and rooms, then import.',
                'Check snap, wall type, and room outlines before you generate panels.',
            ] },
            { type: 'note', text: 'The import block may show **In development**. The button still runs **Import plan**. Imported geometry is a starting point.' },
        ],
    },
    {
        id: 'chat',
        group: 'projects',
        roles: ['admin', 'drafter'],
        title: 'Chat assistant',
        keywords: 'chatbot fab create project folder rooms temperature floor ceiling joints',
        blocks: [
            { type: 'p', text: 'On Home, editors see a blue chat button in the lower right.' },
            { type: 'h3', text: 'If you have never used it' },
            { type: 'steps', items: [
                'Click the chat button.',
                'Tap **I’m new — guide me**.',
                'Answer one question at a time. You can tap a suggestion chip instead of typing.',
                'When the summary appears, tap **Create project** (or type **create**).',
            ] },
            { type: 'p', text: 'You can also paste the whole job in one message. Tap **Show an example** for a template. Type **restart** to start over.' },
            { type: 'h3', text: 'What it can ask' },
            { type: 'steps', items: [
                'Folder — **place it** in an existing folder, **create a new folder**, or **uncategorized**.',
                'Project name.',
                'Site size, for example **5000 × 8500 × 6000** (mm) or **5m × 8.5m × 6m**. Small numbers without a unit are metres.',
                'Rooms: names, then each room’s size in one reply. You can add height, temperature, and floor in the same line.',
                'Confirm the summary, then **create**.',
            ] },
            { type: 'note', text: 'If you only send a room size, the assistant uses project height, 0°C, slab 100 mm, ceiling yes, and PPGI walls. Wall thickness defaults to 100 mm. It does not set ceiling joints — open **Joint Configuration** on the Ceiling tab after generation.' },
        ],
    },
    {
        id: 'workspace',
        group: 'draw',
        title: 'Project workspace',
        keywords: 'tabs wall ceiling floor summary 2d 3d undo redo versions share comments plan notes level manage',
        blocks: [
            { type: 'p', text: 'The header shows the project name and site size (W × L × H mm).' },
            { type: 'note', roles: ['salesman'], text: 'The left sidebar shows **View-only mode**. You can still switch tabs, open 3D, export, and leave **Feedback**.' },
            { type: 'note', roles: ['guest'], text: 'On a view-only share link you can browse plans and 3D. Sign in as Admin or Drafter to edit.' },
            { type: 'img', roles: ['admin', 'drafter'], src: '/manual/05-wall-plan.png', alt: 'Project workspace Wall tab', caption: 'Plan tabs, **2D** / **3D**, **Undo**, **Redo**, **Share**, and **Enter Edit Mode**.' },
            { type: 'img', roles: ['salesman'], src: '/manual/05-wall-plan.png', alt: 'Project workspace Wall tab', caption: 'Review the drawing. Drawing tools and **Share** are hidden.' },
            { type: 'img', roles: ['guest'], src: '/manual/05-wall-plan.png', alt: 'Project workspace Wall tab', caption: 'A share link opens this project only — not the project list.' },
            { type: 'h3', text: 'Tabs' },
            { type: 'table', headers: ['Tab', 'When it is available'], rows: [
                ['Wall', 'Always.'],
                ['Ceiling', 'After at least one room exists.'],
                ['Floor', 'After rooms exist. Grey until then: **Add rooms first**.'],
                ['Summary & Install Time', 'Hidden on view-only share links.'],
            ] },
            { type: 'h3', roles: ['admin', 'drafter'], text: 'Start drawing' },
            { type: 'steps', roles: ['admin', 'drafter'], items: [
                'Stay on **Wall** and **2D View**.',
                'Click **Show Controls** if the sidebar is hidden.',
                'Click **Enter Edit Mode**. Drawing tools appear.',
                'Pick a tool, for example **Add Wall**. The canvas hint tells you what to click.',
                'Press **Esc** or click **Cancel** to leave a tool. Click **Exit Edit Mode** when you are done.',
                '**Undo** (Ctrl+Z) and **Redo** (Ctrl+Y) apply to this session. Wait a moment after undo before drawing again.',
            ] },
            { type: 'table', roles: ['admin', 'drafter'], headers: ['Control', 'Notes'], rows: [
                ['Versions', 'Save, view, compare, restore, or delete a snapshot. Opening a project always shows the original (version 0).'],
                ['Share', 'View-only or editable link.'],
                ['Comments', 'Review salesman feedback.'],
                ['Plan notes', 'Text boxes on the Wall plan.'],
                ['Level', 'Active storey.'],
                ['Manage', 'Add, edit, or delete a level.'],
            ] },
            { type: 'h3', roles: ['salesman'], text: 'Header' },
            { type: 'table', roles: ['salesman'], headers: ['Control', 'Notes'], rows: [
                ['Versions', 'Open a saved snapshot to view, or compare snapshots side by side. You cannot save, restore, or delete.'],
                ['Feedback', 'Leave a comment. Optionally select walls on the plan.'],
                ['Level', 'Switch storey to review.'],
                ['2D / 3D', 'Plans or the model. Tour works.'],
            ] },
        ],
    },
    {
        id: 'zoom',
        group: 'draw',
        title: 'Zoom, pan, and labels',
        keywords: 'zoom in zoom out reset pan right-click wheel overall wall dimensions panel lines purple blue orange outer corner extension door',
        blocks: [
            { type: 'p', text: 'These controls sit on every 2D plan (Wall, Ceiling, Floor).' },
            { type: 'h3', text: 'Move around the plan' },
            { type: 'steps', items: [
                'Use **+** and **−** to zoom. The mouse wheel does not zoom the 2D plan.',
                'Click **Reset Zoom** so the full site fits.',
                'On the Wall plan, right-click and drag to pan. On Ceiling and Floor, left-drag.',
            ] },
            { type: 'h3', text: 'Dimension labels (Wall plan)' },
            { type: 'table', headers: ['Checkbox', 'Colour', 'Meaning'], rows: [
                ['Overall project dimensions', 'Purple', 'Full site width and length'],
                ['Wall dimensions', 'Blue', 'Length of each wall'],
                ['Side Panel dimensions', 'Orange', 'Panel-module sizes along a wall'],
                ['Panel division lines', '—', 'Seam lines only (1130 mm ends are not hatched)'],
            ] },
            { type: 'p', text: 'Dashed extension lines follow the **drawn wall**. 45° joints meet the outer corners. **Butt-in** walls stop at the shortened end (where they meet the other wall), not through the host wall. Orange side-panel sizes use those same ends. Ceiling and Floor room or panel dimensions use the same end-to-end attach.' },
            { type: 'note', text: 'If a label would cover a door, it moves beside or outside the opening. The same side-panel size is shown once per direction (305 at the top is not repeated at the bottom). Crowded labels may hide rather than sit on the wrong wall. **Project Dimensions Exceeded** means drawing ran outside the site envelope.' },
        ],
    },
    {
        id: 'add-wall',
        group: 'draw',
        roles: ['admin', 'drafter'],
        title: 'Add Wall',
        keywords: 'add wall partition height thickness snap length finishes ppgi deduct auto-split',
        blocks: [
            { type: 'img', src: '/manual/06-drawing-tools.png', alt: 'Drawing Tools in edit mode', caption: '**Add Wall**, **Edit Wall**, **Merge Walls**, **Split Wall**, **Define Room**, **Add Door**, **Edit Door**.' },
            { type: 'steps', items: [
                'Click **Enter Edit Mode**, then **Add Wall**.',
                'Set type, height, thickness, and face finishes.',
                'Click the start point, then the end point. Endpoints snap to existing walls.',
                'If the end is not snapped, **Enter Wall Length** opens. Type mm, then **Confirm**.',
                'Press **Esc** or right-click to cancel an unfinished wall.',
                'Draw a closed outline before you define a room.',
                'Click **Exit Edit Mode**, then set joints at corners.',
            ] },
            { type: 'table', headers: ['Option', 'What it does'], rows: [
                ['Wall Type', 'Wall or Partition'],
                ['Deduct new wall thickness from host at free corners', 'Shortens the host so the new wall sits flush'],
                ['Auto-split walls at intersections', 'Cuts existing walls where the new wall crosses them'],
                ['Face Finishes', 'Inner and outer material (PPGI, S/Steel, PVC) and sheet thickness'],
            ] },
            { type: 'p', text: 'Snap badges show horizontal, vertical, perpendicular, along slant, or free angle.' },
        ],
    },
    {
        id: 'edit-wall',
        group: 'draw',
        roles: ['admin', 'drafter'],
        title: 'Edit, merge, and split walls',
        keywords: 'edit wall lock length gap-fill windows merge confirm split distance joints ctrl-click',
        blocks: [
            { type: 'h3', text: 'Edit Wall' },
            { type: 'steps', items: [
                'Enter Edit Mode, then click **Edit Wall**.',
                'Click a wall. Tick **Select Multiple Walls** to edit several at once.',
                'Click **Show Edit Wall Form**.',
                'Change position, height, thickness, type, or finishes. Use the padlock to lock a field.',
                'Optional: **Advanced Options** → **Enable Gap-Fill**. Gap-fill walls cannot host doors.',
                'To add a window, save the wall first if **Add Window** is disabled.',
                'Click **Save**, or **Remove Wall**.',
            ] },
            { type: 'h3', text: 'Merge Walls' },
            { type: 'steps', items: [
                'Enter Edit Mode, then click **Merge Walls**.',
                'Click a run of walls that meet end-to-end and share type, height, thickness, and finishes.',
                'Click **Confirm Merge**.',
            ] },
            { type: 'h3', text: 'Split Wall' },
            { type: 'steps', items: [
                'Enter Edit Mode, then click **Split Wall**.',
                'Click the wall, then click the split point.',
                'Or type **Distance from start (mm)** and click **Split at Distance**.',
                '**Clear Selection** drops the wall without splitting.',
            ] },
            { type: 'h3', text: 'Show Plan Details' },
            { type: 'ul', items: [
                '**View Material Needed** — panel and leftover summary.',
                '**Wall Elevations** — **Generate Elevations** or **Hide Elevations**.',
                '**Calculate Wall Panels** — see Wall panel calculation.',
            ] },
        ],
    },
    {
        id: 'joints',
        group: 'draw',
        title: 'Wall joints',
        keywords: 'configure joints butt-in 45 cut none deduct thickness flip wall order intersection corner',
        blocks: [
            { type: 'p', roles: ['admin', 'drafter'], text: 'A joint is where two walls meet. This is separate from ceiling joints (AA11, Cut L, Cut 45).' },
            { type: 'note', roles: ['salesman'], text: 'Editors set wall joints. You still see the result in 2D, 3D, and export.' },
            { type: 'steps', roles: ['admin', 'drafter'], items: [
                'Finish drawing, then click **Exit Edit Mode**.',
                'Click a wall corner. **Configure Joints** opens.',
                'Set **None**, **Butt-in**, or **45° Cut**.',
                'For Butt-in, optionally tick **Deduct joining wall thickness**. Use **Flip Wall Order** if the wrong wall shortens.',
                'To set several corners the same, click more corners, pick a type, then **Apply type to all**.',
                'Click **Save Changes**. Recalculate wall panels after joints change.',
            ] },
            { type: 'table', roles: ['admin', 'drafter'], headers: ['Type', 'Meaning'], rows: [
                ['None', 'Default meeting. No special cut.'],
                ['Butt-in', 'One wall butts into the other.'],
                ['45° Cut', 'Miter at the corner.'],
            ] },
            { type: 'p', roles: ['admin', 'drafter'], text: 'Ctrl+click a corner to remove it from the selection. Ceiling joints are on the Ceiling tab, on each room.' },
        ],
    },
    {
        id: 'rooms',
        group: 'rooms',
        roles: ['admin', 'drafter'],
        title: 'Define Room',
        keywords: 'define room polygon temperature height slab panel none base elevation variable walls',
        blocks: [
            { type: 'steps', items: [
                'Draw a closed loop of walls first.',
                'Enter Edit Mode, then click **Define Room**.',
                'Click wall corners in order around the room.',
                'Right-click undoes the last point. **Esc** cancels.',
                'Click the first point again to close. The **Create Room** form opens.',
                'Enter name, temperature, height, floor type, and optional notes.',
                'Click **Create room**.',
            ] },
            { type: 'h3', text: 'Room form' },
            { type: 'table', headers: ['Field', 'Notes'], rows: [
                ['Temperature (°C)', 'A single value or a range, such as 5 or 2–6'],
                ['Room height (mm)', 'Values of 50 or less are treated as metres'],
                ['Variable wall heights', 'For sloped roofs. Room height will not rewrite wall heights'],
                ['Base elevation (mm)', 'Floor height vs the storey datum'],
                ['Floor Type', 'Slab, Panel, or None. Only Panel rooms generate on the Floor tab'],
            ] },
            { type: 'h3', text: 'Room labels' },
            { type: 'p', text: 'Click a label to select it. Double-click to edit the name, height, or description. Drag to move it (not during Define Room).' },
        ],
    },
    {
        id: 'doors',
        group: 'rooms',
        roles: ['admin', 'drafter'],
        title: 'Doors and windows',
        keywords: 'add door edit door swing slide dock interior exterior window glass louver',
        blocks: [
            { type: 'p', text: '**Add Door** places an opening on a wall. Gap-fill walls are skipped. The opening stays fully on the wall.' },
            { type: 'h3', text: 'Add a door' },
            { type: 'steps', items: [
                'Enter Edit Mode, then click **Add Door**.',
                'Click the host wall.',
                'Set type (Swing, Slide, or Dock Door) and single- or double-sided.',
                'Set width, height, and thickness.',
                'Use the position slider, or **From Left to Door Edge**.',
                'Choose interior or exterior, or click **Flip Installing Side**.',
                'For swing or slide, choose left or right, or click **Flip Opening Direction**. Dock doors have no swing direction.',
                'Optional: **Windows on Door** → **Add Window**.',
                'Click **Add Door**. Later, use **Edit Door** and click the symbol to change or delete it.',
            ] },
            { type: 'h3', text: 'Windows on a wall' },
            { type: 'p', text: 'From **Edit Wall**, use **Add Window**. Set width, height, position along the wall, and height from the floor, then **Save**.' },
            { type: 'p', text: 'In **3D View**, click a door, then **Open Door** or **Close Door** (or Space). In the tour, press **E**.' },
        ],
    },
    {
        id: 'levels',
        group: 'rooms',
        roles: ['admin', 'drafter'],
        title: 'Levels',
        keywords: 'add level edit level delete storey elevation copy layout draw area',
        blocks: [
            { type: 'p', text: 'The level dropdown on the Wall tab sets which storey you are drawing. Each storey has its own walls, rooms, doors, and panels. Ground floor cannot be deleted.' },
            { type: 'h3', text: 'Add a level' },
            { type: 'steps', items: [
                'Click **Manage** → **Add Level**.',
                'Step 1: name the storey. Optionally copy a layout from another storey.',
                'Step 2: tick rooms to copy walls from, or **Draw Area** for a custom outline.',
                'Step 3: set elevation, default height, and room heights.',
                'Click **Create Storey**.',
            ] },
            { type: 'h3', text: 'Copy walls onto this level' },
            { type: 'steps', items: [
                'Switch the level dropdown to the storey that should receive the walls.',
                'Click **Manage** → **Edit Level**.',
                'Tick rooms on other storeys. Rooms already copied cannot be ticked again.',
                'Set base elevation and room height if you need different values.',
                'Click **Add Selected Rooms**.',
                '**Clear Selection** unchecks without copying. **Close** leaves the mode.',
            ] },
            { type: 'h3', text: 'Delete a level' },
            { type: 'p', text: '**Manage** → **Delete Level**. Confirm. Rooms, walls, and panels on that storey are removed.' },
        ],
    },
    {
        id: 'notes',
        group: 'rooms',
        title: 'Notes, comments, versions, and sharing',
        keywords: 'plan notes arrow delete feedback comments select walls share versions restore original snapshot compare view only editable copy link',
        blocks: [
            { type: 'h3', roles: ['admin', 'drafter'], text: 'Plan notes' },
            { type: 'steps', roles: ['admin', 'drafter'], items: [
                'On the Wall tab, click **Plan notes**.',
                'Click the plan to place a box, or drag to draw a custom size.',
                'Double-click (or press Enter) and type. Enter or click away saves. Esc cancels.',
                'Drag to move. Use the resize handle. **Arrow** adds a leader to a point on the plan.',
                'Delete or Backspace removes the selected note. **Done** leaves note mode.',
            ] },
            { type: 'h3', roles: ['admin', 'drafter'], text: 'Comments' },
            { type: 'steps', roles: ['admin', 'drafter'], items: [
                'Click **Comments**.',
                'Click a comment to highlight the walls the salesman selected.',
                'Click **Mark as done** when the work is finished. **Reopen** sets it back to Open.',
                'Fix the drawing if needed, then close the panel.',
            ] },
            { type: 'h3', roles: ['salesman'], text: 'Leave Feedback' },
            { type: 'steps', roles: ['salesman'], items: [
                'Open the project, then click **Feedback**.',
                'Type your note.',
                'Optional: click **Select walls on plan**, click the walls, then **Done selecting**.',
                'Click **Add comment**. You cannot change the drawing from this panel.',
            ] },
            { type: 'note', roles: ['salesman'], text: '**Plan notes** and **Share** are hidden. **Versions** lets you view snapshots. Use **Feedback** so an editor sees your notes under **Comments**.' },
            { type: 'h3', roles: ['admin', 'drafter'], text: 'Versions' },
            { type: 'steps', roles: ['admin', 'drafter'], items: [
                'Click **Versions**. Opening a project always shows the original (version 0). Other snapshots appear only after you click **View**. Snapshots do not appear as extra projects on Home.',
                'Optional: type a label such as `Walls complete`, then click **Save version**. The last 20 versions are kept. The canvas then shows that snapshot. Click **Back to original** to return to version 0.',
                '**Compare**: tick 2 to 4 snapshots (including Original), then click **Compare**. Drawings open side by side. View only — the live project is unchanged.',
                '**View** opens that snapshot in this project, including Original. It always shows the **Wall** plan first; then you can open Ceiling or Floor for that same snapshot. Click **Back to original** to return to version 0.',
                '**Restore** loads that snapshot onto the canvas so you can edit from it. After restoring a later version, Original also has Restore so you can load version 0 again. The frozen original stays until you Restore it. Confirm first. Save version afterwards to keep those edits as the next snapshot. Comments, share links, and the project name stay.',
                '**Delete** removes that snapshot only. The original is unchanged. Confirm first.',
            ] },
            { type: 'h3', roles: ['salesman', 'guest'], text: 'Versions' },
            { type: 'steps', roles: ['salesman', 'guest'], items: [
                'Click **Versions**. Opening a project always shows the original (version 0).',
                'Click **View** on a snapshot to look at that drawing. It always opens the wall plan first; then you can open Ceiling or Floor.',
                'Tick 2 to 4 snapshots and click **Compare** to see them side by side. View only.',
                'Click **Back to original** to return to version 0. You cannot save, restore, or delete versions.',
            ] },
            { type: 'h3', roles: ['admin', 'drafter'], text: 'Share' },
            { type: 'img', roles: ['admin', 'drafter'], src: '/manual/12-share.png', alt: 'Share project modal', caption: 'Choose **View only** or **Editable**, then create the link.' },
            { type: 'steps', roles: ['admin', 'drafter'], items: [
                'Click **Share**.',
                'Choose **View only** or **Editable**.',
                'Create the link, then click **Copy**.',
                'View only: the recipient browses this project without signing in. Summary, Comments, and the project list are hidden.',
                'Editable: the recipient must sign in as Admin or Drafter. They still cannot open the project list from that session.',
            ] },
            { type: 'p', roles: ['guest'], text: 'On a view-only share link you can browse this project without signing in. You cannot leave Feedback. On an editable link, sign in as Admin or Drafter to edit.' },
        ],
    },
    {
        id: '3d',
        group: 'views',
        title: '3D view and tour',
        keywords: '3d interior exterior tour wasd space alt shift door fullscreen orbit pinch joystick',
        blocks: [
            { type: 'p', text: 'Click **3D View** in the header. Plan tabs hide until you click **2D View**. Wall faces use a micro-ribbed panel finish, and panel joints are thin seams: from far away both read as smooth off-white, and they show when you zoom in or walk up in **Tour**. Sliding doors show an aluminium edge frame, a top track, and a pull handle. Door and wall windows are thin glass set in the middle of the panel, not as thick as the insulated leaf.' },
            { type: 'img', src: '/manual/08-3d-view.png', alt: '3D view toolbar', caption: 'Interior / Exterior, **Tour**, panel lines, and **Fullscreen** sit above the model.' },
            { type: 'h3', text: 'Orbit' },
            { type: 'steps', items: [
                'Click **3D View** and wait for the model.',
                'Left-drag to rotate. Right-drag to pan. Scroll to zoom.',
                'Click **Switch to Interior** for a cutaway, or **Switch to Exterior** for the full shell.',
                'Click **Hide Panel Lines** to hide wall seams.',
                'Click a door, then **Open Door** or **Close Door** (or Space).',
                'Click **Fullscreen** to enlarge. Esc leaves it.',
            ] },
            { type: 'h3', text: 'Start a tour' },
            { type: 'steps', items: [
                'Click **Tour**.',
                'Click the floor inside a room.',
                'Click **Start tour**, or press Enter. If that spot is blocked, click another point.',
            ] },
            { type: 'h3', text: 'Desktop tour' },
            { type: 'p', text: 'Click the model to capture the mouse. WASD walks. Shift sprints. Space flies up. Left Alt flies down. **E** opens or closes a facing door. Esc exits. You collide with walls; open doors are passages.' },
            { type: 'h3', text: 'Mobile tour' },
            { type: 'p', text: 'Left stick moves. Right side looks. Tap **Open/Close door**. Use the fly up and fly down buttons. **FULL** toggles fullscreen.' },
        ],
    },
    {
        id: 'ceiling',
        group: 'views',
        title: 'Ceiling plan',
        keywords: 'generate ceiling orientation joints aa11 cut l cut 45 nylon hanger alu suspension rails merge swap unmerge merged zone',
        blocks: [
            { type: 'p', text: 'Open the **Ceiling** tab after rooms exist.' },
            { type: 'note', roles: ['salesman'], text: 'You can view and zoom. You cannot generate, merge, set joints, or edit supports.' },
            { type: 'img', roles: ['admin', 'drafter'], src: '/manual/09-ceiling.png', alt: 'Ceiling plan generator', caption: 'Orientation, panel size, materials, then **Generate Ceiling Plan**.' },
            { type: 'img', roles: ['salesman', 'guest'], src: '/manual/09-ceiling.png', alt: 'Ceiling plan', caption: 'Review a ceiling that an editor already generated.' },
            { type: 'h3', roles: ['admin', 'drafter'], text: 'Generate' },
            { type: 'steps', roles: ['admin', 'drafter'], items: [
                'Set **Level** and **View** (all rooms, or one room).',
                'Choose an orientation strategy.',
                'Set panel width and length, thickness, and face materials.',
                'Select a room. Open **Joint Configuration**. Set each wall, then **Save Now**.',
                'To skip a room, tick **This room is excluded from ceiling generation**.',
                'Click **Generate Ceiling Plan**. Generate again after you change rooms, joints, or sizes.',
            ] },
            { type: 'h3', text: 'Ceiling joints' },
            { type: 'p', roles: ['admin', 'drafter'], text: 'Select a room, then **Joint Configuration**. This is how the ceiling meets each wall — not the same as wall-plan joints.' },
            { type: 'p', roles: ['salesman'], text: 'You can read the joint types. Dropdowns and **Save Now** are disabled.' },
            { type: 'table', headers: ['Joint', 'Meaning'], rows: [
                ['Not Set', 'No type stored yet'],
                ['AA11', 'No cut. Wall height becomes room height minus ceiling thickness'],
                ['Cut L', 'L-shaped cut. Set Horizontal Extension if needed'],
                ['Cut 45', '45-degree cut marker. No automatic height change'],
            ] },
            { type: 'p', roles: ['admin', 'drafter'], text: 'Quick actions: **Set All AA11**, **Set All Cut L**, **Clear All**. Then **Save Now**, and generate again so panels match.' },
            { type: 'h3', roles: ['admin', 'drafter'], text: 'Merge rooms' },
            { type: 'steps', roles: ['admin', 'drafter'], items: [
                'Click **Merge Ceilings**. Rooms must have matching heights.',
                'Tick two or more rooms.',
                'Click **Merge Selected Rooms**. Internal walls of the zone are AA11.',
                'Under **Existing Merged Zones**, click **Unmerge Zone** to split them again.',
            ] },
            { type: 'h3', roles: ['admin', 'drafter'], text: 'Swap two panels' },
            { type: 'steps', roles: ['admin', 'drafter'], items: [
                'Generate a ceiling, then click one panel. That is Panel A.',
                'Click a second panel in the same room. That is Panel B.',
                'Click **Swap Selected Panels**.',
                '**Clear Selection** drops the pair without swapping.',
            ] },
            { type: 'h3', roles: ['admin', 'drafter'], text: 'Support tools' },
            { type: 'steps', roles: ['admin', 'drafter'], items: [
                'Click **Show Support Tools**.',
                'Tick **Auto nylon on long panels** if hangers should place automatically. This also applies to **merged zones**, not only single rooms.',
                'For rails, tick **Alu suspension**, then **Draw support line**. Click start, then end.',
                'For a manual hanger, click **Add nylon hanger**, click a panel, enter the distance, then add.',
                'Click a hanger or rail to edit it, then **Done** or delete it.',
                '**Clear all supports** removes hangers and rails.',
            ] },
            { type: 'p', roles: ['admin', 'drafter'], text: 'Red nylon markers shrink when the plan is zoomed out so they stay smaller than the panels, and grow again when you zoom in.' },
            { type: 'h3', text: 'Plan details' },
            { type: 'p', text: '**Show Plan Details** lists full and cut panels, waste, and legends. Overall outline is blue. Full panels are grey. Cut panels are red.' },
        ],
    },
    {
        id: 'floor',
        group: 'views',
        title: 'Floor plan',
        keywords: 'generate floor slab size panel dimensions waste orientation',
        blocks: [
            { type: 'p', text: 'Open the **Floor** tab. Only rooms whose floor type is **Panel** get a panel layout. Slab rooms use **Slab size** for take-off.' },
            { type: 'h3', roles: ['admin', 'drafter'], text: 'Generate' },
            { type: 'steps', roles: ['admin', 'drafter'], items: [
                'Confirm each room’s floor type is **Panel** if you need a panel layout.',
                'Open the Floor tab. Set **Level** if you have more than one storey.',
                'Tick **Room dimensions** or **Panel dimensions** to show labels. Extension lines meet the outer ends of the span, not the middle of the wall.',
                'Set orientation and panel size.',
                'Click **Generate Floor Plan**. Generate again after you change rooms or sizes.',
                'For slab floors, set **Slab size** and read the slab summary.',
            ] },
            { type: 'note', roles: ['salesman'], text: 'You can view a generated floor and zoom. You cannot generate or change the layout.' },
            { type: 'img', roles: ['admin', 'drafter'], src: '/manual/10-floor.png', alt: 'Floor plan generator', caption: 'Orientation, panel size, then **Generate Floor Plan**.' },
            { type: 'img', roles: ['salesman', 'guest'], src: '/manual/10-floor.png', alt: 'Floor plan', caption: 'Review panel floors that an editor already generated.' },
        ],
    },
    {
        id: 'panels',
        group: 'output',
        roles: ['admin', 'drafter'],
        title: 'Wall panel calculation',
        keywords: 'calculate wall panels optimized default leftover material analysis refresh walls',
        blocks: [
            { type: 'p', text: 'On the Wall tab, open **Show Plan Details**. Calculate after walls, joints, doors, or storeys change.' },
            { type: 'steps', items: [
                'Click **Show Plan Details** if the side panel is collapsed.',
                'Click **Calculate Wall Panels (Optimized)** for less waste, or **(Default)** for a straightforward cut list.',
                'Use **Try Optimized Method** or **Try Default Method** if you want the other approach, then calculate again.',
                'Click **Show Panel Table** to read full, cut, and leftover rows.',
                'Click **Refresh Walls** if you added storeys and counts look old.',
            ] },
            { type: 'note', text: 'Stale results are flagged when the wall layout has changed. Recalculate after joints or doors change.' },
        ],
    },
    {
        id: 'export',
        group: 'output',
        title: 'Summary and export',
        keywords: 'export project report excel pdf elevations panels per day working days fetch data',
        blocks: [
            { type: 'p', text: 'Open **Summary & Install Time**. This tab is hidden on view-only share links.' },
            { type: 'img', src: '/manual/11-summary.png', alt: 'Summary and installation estimator', caption: 'Counts, rates per day, and **Export Project Report**.' },
            { type: 'steps', items: [
                'If counts look stale, click **Refresh Data**. Optionally **Fetch Data & Images** for plan pictures.',
                'Set panels, doors, and slabs per day. Working days include a 20% buffer.',
                'Click **Export Project Report**.',
                'Choose portrait or landscape. Tick elevations if you want them.',
                'Click **Download Excel** and/or **Generate & Download PDF**.',
            ] },
            { type: 'note', roles: ['admin', 'drafter'], text: 'If panels are missing, generate ceiling and floor first, then calculate wall panels.' },
            { type: 'note', roles: ['salesman'], text: 'You can export. You cannot generate missing plans — ask an editor if the report is empty.' },
        ],
    },
    {
        id: 'shortcuts',
        group: 'ref',
        title: 'Keyboard shortcuts',
        keywords: 'ctrl z y esc delete backspace wasd shift space alt enter f2',
        blocks: [
            { type: 'table', roles: ['admin', 'drafter'], headers: ['Shortcut', 'Action'], rows: [
                ['Ctrl+Z / Ctrl+Y', 'Undo / Redo'],
                ['Esc', 'Cancel drawing, close a tool, or exit tour / fullscreen'],
                ['Right-click + drag', 'Pan the wall plan'],
                ['Right-click while drawing', 'Cancel the wall, or undo the last room point'],
                ['Ctrl+click on a joint', 'Remove it from the selection'],
                ['Enter / F2', 'Edit a selected plan note'],
                ['Delete / Backspace', 'Delete a selected note, hanger, or rail'],
            ] },
            { type: 'table', roles: ['salesman', 'guest'], headers: ['Shortcut', 'Action'], rows: [
                ['Esc', 'Close Help, or exit tour / fullscreen'],
                ['Right-click + drag', 'Pan the wall plan'],
            ] },
            { type: 'h3', text: '3D tour' },
            { type: 'table', headers: ['Key', 'Action'], rows: [
                ['W A S D / arrows', 'Walk'],
                ['Shift', 'Sprint'],
                ['Space / Left Alt', 'Fly up / fly down'],
                ['E', 'Open or close the facing door'],
                ['Esc', 'Exit tour'],
            ] },
        ],
    },
    {
        id: 'tips',
        group: 'ref',
        title: 'Tips',
        keywords: 'grey tabs database invalid project salesman joints purple dimensions tour blocked',
        blocks: [
            { type: 'ul', roles: ['admin', 'drafter'], items: [
                'Draw walls before rooms. **Define Room** needs a closed loop.',
                'Ceiling and Floor stay grey until at least one room exists.',
                'Floor generation only includes rooms with floor type **Panel**.',
                'Recalculate wall panels after any wall, door, or joint change.',
                'Purple overall, blue wall, and orange side-panel dimensions follow the drawn wall: outer corners for 45° joints, the shortened face for **butt-in**. If the purple size still looks wrong, drawing may sit outside the site envelope — enlarge the project or pull walls back in.',
                'A tour start must be on the floor inside a room, not inside a wall.',
                'Gap-fill walls cannot host doors.',
                'Ground floor cannot be deleted.',
                'Save a **version** at a milestone (walls done, before a big change). Restore loads that snapshot for editing without changing version 0. Delete a snapshot if you no longer need it.',
                '**Database connection failed** means the API is not reachable. Start the Django server and refresh.',
            ] },
            { type: 'ul', roles: ['salesman'], items: [
                'Home only lists projects assigned to you. If one is missing, ask an editor to tick your account in **Visibility**.',
                'You can navigate tabs, view 3D, export, and leave **Feedback**. You cannot edit.',
                'Grey Ceiling or Floor tabs mean an editor has not defined rooms yet.',
                'If a plan is empty, ask an editor to generate it. You cannot generate.',
                'A tour start must be on the floor inside a room.',
            ] },
            { type: 'ul', roles: ['guest'], items: [
                'Ask an administrator for an account. There is no public registration.',
                '**Continue as guest** does not open Home. Use a share link to browse one project.',
                'Editable share links show **Login to edit**. Only Admin or Drafter can draw.',
            ] },
        ],
    },
];

export function sectionsForRole(role) {
    const viewRole = HELP_ROLE_OPTIONS.some((option) => option.id === role) ? role : 'guest';
    return MANUAL_SECTIONS
        .filter((section) => itemVisibleForRole(section, viewRole))
        .map((section) => ({
            ...section,
            blocks: (section.blocks || []).filter((block) => itemVisibleForRole(block, viewRole)),
        }))
        .filter((section) => section.blocks.length > 0);
}

export function searchManualSections(query, role) {
    const sections = sectionsForRole(role);
    const q = String(query || '').trim().toLowerCase();
    if (!q) return sections;
    return sections.filter((section) => {
        const hay = [
            section.title,
            section.keywords,
            ...section.blocks.flatMap((block) => {
                if (block.text) return [block.text];
                if (block.items) return block.items;
                if (block.rows) return block.rows.flat();
                if (block.headers) return block.headers;
                if (block.type === 'img') return [block.alt, block.caption, block.src];
                return [];
            }),
        ].join(' ').toLowerCase();
        return hay.includes(q);
    });
}
